.class public final Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
.super Lcom/google/protobuf/GeneratedMessageLite;
.source "Data.java"

# interfaces
.implements Lcom/google/wireless/tacotruck/proto/Data$HangoutDataOrBuilder;


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/google/wireless/tacotruck/proto/Data;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "HangoutData"
.end annotation

.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;,
        Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    }
.end annotation


# static fields
.field private static final defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

.field private static final serialVersionUID:J


# instance fields
.field private activeOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private bitField0_:I

.field private broadcastId_:Ljava/lang/Object;

.field private idIsAutogenerated_:Z

.field private inactiveOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private memoizedIsInitialized:B

.field private memoizedSerializedSize:I

.field private notificationId_:Lcom/google/protobuf/LazyStringList;

.field private roomDomain_:Ljava/lang/Object;

.field private roomId_:Ljava/lang/Object;

.field private subject_:Ljava/lang/Object;

.field private type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

.field private url_:Ljava/lang/Object;


# direct methods
.method static constructor <clinit>()V
    .registers 2

    .prologue
    .line 39392
    new-instance v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    const/4 v1, 0x1

    invoke-direct {v0, v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;-><init>(Z)V

    sput-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    .line 39393
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    invoke-direct {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->initFields()V

    .line 39394
    return-void
.end method

.method private constructor <init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;)V
    .registers 3
    .parameter "builder"

    .prologue
    const/4 v0, -0x1

    .line 38189
    invoke-direct {p0, p1}, Lcom/google/protobuf/GeneratedMessageLite;-><init>(Lcom/google/protobuf/GeneratedMessageLite$Builder;)V

    .line 38492
    iput-byte v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    .line 38536
    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    .line 38190
    return-void
.end method

.method synthetic constructor <init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;Lcom/google/wireless/tacotruck/proto/Data$1;)V
    .registers 3
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    invoke-direct {p0, p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;-><init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;)V

    return-void
.end method

.method private constructor <init>(Z)V
    .registers 3
    .parameter "noInit"

    .prologue
    const/4 v0, -0x1

    .line 38191
    invoke-direct {p0}, Lcom/google/protobuf/GeneratedMessageLite;-><init>()V

    .line 38492
    iput-byte v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    .line 38536
    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    .line 38191
    return-void
.end method

.method static synthetic access$51902(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$52002(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$52102(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$52200(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;
    .registers 2
    .parameter "x0"

    .prologue
    .line 38184
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object v0
.end method

.method static synthetic access$52202(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object p1
.end method

.method static synthetic access$52300(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;
    .registers 2
    .parameter "x0"

    .prologue
    .line 38184
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object v0
.end method

.method static synthetic access$52302(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object p1
.end method

.method static synthetic access$52402(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$52500(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;
    .registers 2
    .parameter "x0"

    .prologue
    .line 38184
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object v0
.end method

.method static synthetic access$52502(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/protobuf/LazyStringList;)Lcom/google/protobuf/LazyStringList;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object p1
.end method

.method static synthetic access$52602(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    return-object p1
.end method

.method static synthetic access$52702(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-boolean p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    return p1
.end method

.method static synthetic access$52802(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$52902(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;I)I
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 38184
    iput p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    return p1
.end method

.method private getBroadcastIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 38469
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 38470
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 38471
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 38473
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 38476
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method public static getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 1

    .prologue
    .line 38195
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    return-object v0
.end method

.method private getRoomDomainBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 38403
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 38404
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 38405
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 38407
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 38410
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getRoomIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 38265
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 38266
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 38267
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 38269
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 38272
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getSubjectBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 38329
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 38330
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 38331
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 38333
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 38336
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getUrlBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 38297
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 38298
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 38299
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 38301
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 38304
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private initFields()V
    .registers 2

    .prologue
    .line 38481
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 38482
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 38483
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 38484
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    .line 38485
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    .line 38486
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 38487
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 38488
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 38489
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    .line 38490
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 38491
    return-void
.end method

.method public static newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 1

    .prologue
    .line 38665
    #calls: Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->access$51700()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public static newBuilder(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2
    .parameter "prototype"

    .prologue
    .line 38668
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {v0, p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method


# virtual methods
.method public getActiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 38354
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getActiveOccupantCount()I
    .registers 2

    .prologue
    .line 38351
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getActiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 38344
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getActiveOccupantOrBuilder(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;
    .registers 3
    .parameter "index"

    .prologue
    .line 38358
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;

    return-object v0
.end method

.method public getActiveOccupantOrBuilderList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;",
            ">;"
        }
    .end annotation

    .prologue
    .line 38348
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getBroadcastId()Ljava/lang/String;
    .registers 5

    .prologue
    .line 38455
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 38456
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 38457
    check-cast v1, Ljava/lang/String;

    .line 38465
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 38459
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 38461
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 38462
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 38463
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 38465
    goto :goto_8
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 38184
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 2

    .prologue
    .line 38199
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    return-object v0
.end method

.method public getIdIsAutogenerated()Z
    .registers 2

    .prologue
    .line 38445
    iget-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    return v0
.end method

.method public getInactiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 38375
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getInactiveOccupantCount()I
    .registers 2

    .prologue
    .line 38372
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getInactiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 38365
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getInactiveOccupantOrBuilder(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;
    .registers 3
    .parameter "index"

    .prologue
    .line 38379
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;

    return-object v0
.end method

.method public getInactiveOccupantOrBuilderList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;",
            ">;"
        }
    .end annotation

    .prologue
    .line 38369
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getNotificationId(I)Ljava/lang/String;
    .registers 3
    .parameter "index"

    .prologue
    .line 38425
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1}, Lcom/google/protobuf/LazyStringList;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/lang/String;

    return-object v0
.end method

.method public getNotificationIdCount()I
    .registers 2

    .prologue
    .line 38422
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v0

    return v0
.end method

.method public getNotificationIdList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .prologue
    .line 38419
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object v0
.end method

.method public getRoomDomain()Ljava/lang/String;
    .registers 5

    .prologue
    .line 38389
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 38390
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 38391
    check-cast v1, Ljava/lang/String;

    .line 38399
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 38393
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 38395
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 38396
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 38397
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 38399
    goto :goto_8
.end method

.method public getRoomId()Ljava/lang/String;
    .registers 5

    .prologue
    .line 38251
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 38252
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 38253
    check-cast v1, Ljava/lang/String;

    .line 38261
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 38255
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 38257
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 38258
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 38259
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 38261
    goto :goto_8
.end method

.method public getSerializedSize()I
    .registers 10

    .prologue
    const/16 v8, 0x8

    const/4 v7, 0x4

    const/4 v6, 0x2

    const/4 v5, 0x1

    .line 38538
    iget v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    .line 38539
    .local v2, size:I
    const/4 v4, -0x1

    if-eq v2, v4, :cond_c

    move v3, v2

    .line 38588
    .end local v2           #size:I
    .local v3, size:I
    :goto_b
    return v3

    .line 38541
    .end local v3           #size:I
    .restart local v2       #size:I
    :cond_c
    const/4 v2, 0x0

    .line 38542
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x1

    if-ne v4, v5, :cond_1c

    .line 38543
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v5, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38546
    :cond_1c
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x2

    if-ne v4, v6, :cond_2b

    .line 38547
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v6, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38550
    :cond_2b
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x4

    if-ne v4, v7, :cond_3b

    .line 38551
    const/4 v4, 0x3

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubjectBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38554
    :cond_3b
    const/4 v1, 0x0

    .local v1, i:I
    :goto_3c
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    if-ge v1, v4, :cond_54

    .line 38555
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v4, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lcom/google/protobuf/MessageLite;

    invoke-static {v7, v4}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38554
    add-int/lit8 v1, v1, 0x1

    goto :goto_3c

    .line 38558
    :cond_54
    const/4 v1, 0x0

    :goto_55
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    if-ge v1, v4, :cond_6e

    .line 38559
    const/4 v5, 0x5

    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v4, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lcom/google/protobuf/MessageLite;

    invoke-static {v5, v4}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38558
    add-int/lit8 v1, v1, 0x1

    goto :goto_55

    .line 38562
    :cond_6e
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x8

    if-ne v4, v8, :cond_7e

    .line 38563
    const/4 v4, 0x6

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomainBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38567
    :cond_7e
    const/4 v0, 0x0

    .line 38568
    .local v0, dataSize:I
    const/4 v1, 0x0

    :goto_80
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v4}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v4

    if-ge v1, v4, :cond_96

    .line 38569
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v4, v1}, Lcom/google/protobuf/LazyStringList;->getByteString(I)Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSizeNoTag(Lcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v0, v4

    .line 38568
    add-int/lit8 v1, v1, 0x1

    goto :goto_80

    .line 38572
    :cond_96
    add-int/2addr v2, v0

    .line 38573
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getNotificationIdList()Ljava/util/List;

    move-result-object v4

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    mul-int/lit8 v4, v4, 0x1

    add-int/2addr v2, v4

    .line 38575
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x10

    const/16 v5, 0x10

    if-ne v4, v5, :cond_b5

    .line 38576
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    invoke-virtual {v4}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->getNumber()I

    move-result v4

    invoke-static {v8, v4}, Lcom/google/protobuf/CodedOutputStream;->computeEnumSize(II)I

    move-result v4

    add-int/2addr v2, v4

    .line 38579
    :cond_b5
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x20

    const/16 v5, 0x20

    if-ne v4, v5, :cond_c6

    .line 38580
    const/16 v4, 0x9

    iget-boolean v5, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 38583
    :cond_c6
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x40

    const/16 v5, 0x40

    if-ne v4, v5, :cond_d9

    .line 38584
    const/16 v4, 0xa

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 38587
    :cond_d9
    iput v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    move v3, v2

    .line 38588
    .end local v2           #size:I
    .restart local v3       #size:I
    goto/16 :goto_b
.end method

.method public getSubject()Ljava/lang/String;
    .registers 5

    .prologue
    .line 38315
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 38316
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 38317
    check-cast v1, Ljava/lang/String;

    .line 38325
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 38319
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 38321
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 38322
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 38323
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 38325
    goto :goto_8
.end method

.method public getType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    .registers 2

    .prologue
    .line 38435
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    return-object v0
.end method

.method public getUrl()Ljava/lang/String;
    .registers 5

    .prologue
    .line 38283
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 38284
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 38285
    check-cast v1, Ljava/lang/String;

    .line 38293
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 38287
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 38289
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 38290
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 38291
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 38293
    goto :goto_8
.end method

.method public hasBroadcastId()Z
    .registers 3

    .prologue
    .line 38452
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x40

    const/16 v1, 0x40

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIdIsAutogenerated()Z
    .registers 3

    .prologue
    .line 38442
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x20

    const/16 v1, 0x20

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomDomain()Z
    .registers 3

    .prologue
    .line 38386
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x8

    const/16 v1, 0x8

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomId()Z
    .registers 3

    .prologue
    const/4 v0, 0x1

    .line 38248
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v0, :cond_8

    :goto_7
    return v0

    :cond_8
    const/4 v0, 0x0

    goto :goto_7
.end method

.method public hasSubject()Z
    .registers 3

    .prologue
    .line 38312
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x4

    const/4 v1, 0x4

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasType()Z
    .registers 3

    .prologue
    .line 38432
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x10

    const/16 v1, 0x10

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasUrl()Z
    .registers 3

    .prologue
    .line 38280
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x2

    const/4 v1, 0x2

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public final isInitialized()Z
    .registers 4

    .prologue
    const/4 v1, 0x1

    .line 38494
    iget-byte v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    .line 38495
    .local v0, isInitialized:B
    const/4 v2, -0x1

    if-eq v0, v2, :cond_b

    if-ne v0, v1, :cond_9

    .line 38498
    :goto_8
    return v1

    .line 38495
    :cond_9
    const/4 v1, 0x0

    goto :goto_8

    .line 38497
    :cond_b
    iput-byte v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    goto :goto_8
.end method

.method public bridge synthetic newBuilderForType()Lcom/google/protobuf/MessageLite$Builder;
    .registers 2

    .prologue
    .line 38184
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->newBuilderForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public newBuilderForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 38666
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic toBuilder()Lcom/google/protobuf/MessageLite$Builder;
    .registers 2

    .prologue
    .line 38184
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->toBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public toBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 38670
    invoke-static {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->newBuilder(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method protected writeReplace()Ljava/lang/Object;
    .registers 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/ObjectStreamException;
        }
    .end annotation

    .prologue
    .line 38595
    invoke-super {p0}, Lcom/google/protobuf/GeneratedMessageLite;->writeReplace()Ljava/lang/Object;

    move-result-object v0

    return-object v0
.end method

.method public writeTo(Lcom/google/protobuf/CodedOutputStream;)V
    .registers 8
    .parameter "output"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    const/16 v5, 0x8

    const/4 v4, 0x4

    const/4 v3, 0x2

    const/4 v2, 0x1

    .line 38503
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSerializedSize()I

    .line 38504
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v2, :cond_15

    .line 38505
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v2, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 38507
    :cond_15
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x2

    if-ne v1, v3, :cond_22

    .line 38508
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v3, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 38510
    :cond_22
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x4

    if-ne v1, v4, :cond_30

    .line 38511
    const/4 v1, 0x3

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubjectBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 38513
    :cond_30
    const/4 v0, 0x0

    .local v0, i:I
    :goto_31
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_47

    .line 38514
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/google/protobuf/MessageLite;

    invoke-virtual {p1, v4, v1}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 38513
    add-int/lit8 v0, v0, 0x1

    goto :goto_31

    .line 38516
    :cond_47
    const/4 v0, 0x0

    :goto_48
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_5f

    .line 38517
    const/4 v2, 0x5

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/google/protobuf/MessageLite;

    invoke-virtual {p1, v2, v1}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 38516
    add-int/lit8 v0, v0, 0x1

    goto :goto_48

    .line 38519
    :cond_5f
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x8

    if-ne v1, v5, :cond_6d

    .line 38520
    const/4 v1, 0x6

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomainBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 38522
    :cond_6d
    const/4 v0, 0x0

    :goto_6e
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v1}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v1

    if-ge v0, v1, :cond_83

    .line 38523
    const/4 v1, 0x7

    iget-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v2, v0}, Lcom/google/protobuf/LazyStringList;->getByteString(I)Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 38522
    add-int/lit8 v0, v0, 0x1

    goto :goto_6e

    .line 38525
    :cond_83
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x10

    const/16 v2, 0x10

    if-ne v1, v2, :cond_94

    .line 38526
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    invoke-virtual {v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->getNumber()I

    move-result v1

    invoke-virtual {p1, v5, v1}, Lcom/google/protobuf/CodedOutputStream;->writeEnum(II)V

    .line 38528
    :cond_94
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x20

    const/16 v2, 0x20

    if-ne v1, v2, :cond_a3

    .line 38529
    const/16 v1, 0x9

    iget-boolean v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 38531
    :cond_a3
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x40

    const/16 v2, 0x40

    if-ne v1, v2, :cond_b4

    .line 38532
    const/16 v1, 0xa

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 38534
    :cond_b4
    return-void
.end method
