.class public final Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
.super Lcom/google/protobuf/GeneratedMessageLite$Builder;
.source "Data.java"

# interfaces
.implements Lcom/google/wireless/tacotruck/proto/Data$HangoutDataOrBuilder;


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "Builder"
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lcom/google/protobuf/GeneratedMessageLite$Builder",
        "<",
        "Lcom/google/wireless/tacotruck/proto/Data$HangoutData;",
        "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;",
        ">;",
        "Lcom/google/wireless/tacotruck/proto/Data$HangoutDataOrBuilder;"
    }
.end annotation


# instance fields
.field private activeOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private bitField0_:I

.field private broadcastId_:Ljava/lang/Object;

.field private idIsAutogenerated_:Z

.field private inactiveOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private notificationId_:Lcom/google/protobuf/LazyStringList;

.field private roomDomain_:Ljava/lang/Object;

.field private roomId_:Ljava/lang/Object;

.field private subject_:Ljava/lang/Object;

.field private type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

.field private url_:Ljava/lang/Object;


# direct methods
.method private constructor <init>()V
    .registers 2

    .prologue
    .line 38677
    invoke-direct {p0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;-><init>()V

    .line 38930
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 38966
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 39002
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 39038
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 39127
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 39216
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 39252
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 39308
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 39332
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 39353
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 38678
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->maybeForceBuilderInitialization()V

    .line 38679
    return-void
.end method

.method static synthetic access$51700()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 1

    .prologue
    .line 38672
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method private static create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 1

    .prologue
    .line 38684
    new-instance v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    invoke-direct {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;-><init>()V

    return-object v0
.end method

.method private ensureActiveOccupantIsMutable()V
    .registers 3

    .prologue
    .line 39041
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x8

    const/16 v1, 0x8

    if-eq v0, v1, :cond_17

    .line 39042
    new-instance v0, Ljava/util/ArrayList;

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-direct {v0, v1}, Ljava/util/ArrayList;-><init>(Ljava/util/Collection;)V

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 39043
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x8

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39045
    :cond_17
    return-void
.end method

.method private ensureInactiveOccupantIsMutable()V
    .registers 3

    .prologue
    .line 39130
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x10

    const/16 v1, 0x10

    if-eq v0, v1, :cond_17

    .line 39131
    new-instance v0, Ljava/util/ArrayList;

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-direct {v0, v1}, Ljava/util/ArrayList;-><init>(Ljava/util/Collection;)V

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 39132
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x10

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39134
    :cond_17
    return-void
.end method

.method private ensureNotificationIdIsMutable()V
    .registers 3

    .prologue
    .line 39254
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x40

    const/16 v1, 0x40

    if-eq v0, v1, :cond_17

    .line 39255
    new-instance v0, Lcom/google/protobuf/LazyStringArrayList;

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-direct {v0, v1}, Lcom/google/protobuf/LazyStringArrayList;-><init>(Ljava/util/List;)V

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 39256
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x40

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39258
    :cond_17
    return-void
.end method

.method private maybeForceBuilderInitialization()V
    .registers 1

    .prologue
    .line 38682
    return-void
.end method


# virtual methods
.method public addActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 39101
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39102
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 39104
    return-object p0
.end method

.method public addActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 39084
    if-nez p2, :cond_8

    .line 39085
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39087
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39088
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 39090
    return-object p0
.end method

.method public addActiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "builderForValue"

    .prologue
    .line 39094
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39095
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 39097
    return-object p0
.end method

.method public addActiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39074
    if-nez p1, :cond_8

    .line 39075
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39077
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39078
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 39080
    return-object p0
.end method

.method public addAllActiveOccupant(Ljava/lang/Iterable;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Iterable",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;)",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;"
        }
    .end annotation

    .prologue
    .line 39108
    .local p1, values:Ljava/lang/Iterable;,"Ljava/lang/Iterable<+Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;>;"
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39109
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-static {p1, v0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->addAll(Ljava/lang/Iterable;Ljava/util/Collection;)V

    .line 39111
    return-object p0
.end method

.method public addAllInactiveOccupant(Ljava/lang/Iterable;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Iterable",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;)",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;"
        }
    .end annotation

    .prologue
    .line 39197
    .local p1, values:Ljava/lang/Iterable;,"Ljava/lang/Iterable<+Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;>;"
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39198
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-static {p1, v0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->addAll(Ljava/lang/Iterable;Ljava/util/Collection;)V

    .line 39200
    return-object p0
.end method

.method public addAllNotificationId(Ljava/lang/Iterable;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Iterable",
            "<",
            "Ljava/lang/String;",
            ">;)",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;"
        }
    .end annotation

    .prologue
    .line 39290
    .local p1, values:Ljava/lang/Iterable;,"Ljava/lang/Iterable<Ljava/lang/String;>;"
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 39291
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-static {p1, v0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->addAll(Ljava/lang/Iterable;Ljava/util/Collection;)V

    .line 39293
    return-object p0
.end method

.method public addInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 39190
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39191
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 39193
    return-object p0
.end method

.method public addInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 39173
    if-nez p2, :cond_8

    .line 39174
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39176
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39177
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 39179
    return-object p0
.end method

.method public addInactiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "builderForValue"

    .prologue
    .line 39183
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39184
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 39186
    return-object p0
.end method

.method public addInactiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39163
    if-nez p1, :cond_8

    .line 39164
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39166
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39167
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 39169
    return-object p0
.end method

.method public addNotificationId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39280
    if-nez p1, :cond_8

    .line 39281
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39283
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 39284
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1}, Lcom/google/protobuf/LazyStringList;->add(Ljava/lang/Object;)Z

    .line 39286
    return-object p0
.end method

.method public bridge synthetic build()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public build()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 3

    .prologue
    .line 38721
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    .line 38722
    .local v0, result:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->isInitialized()Z

    move-result v1

    if-nez v1, :cond_f

    .line 38723
    invoke-static {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->newUninitializedMessageException(Lcom/google/protobuf/MessageLite;)Lcom/google/protobuf/UninitializedMessageException;

    move-result-object v1

    throw v1

    .line 38725
    :cond_f
    return-object v0
.end method

.method public bridge synthetic buildPartial()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 6

    .prologue
    .line 38739
    new-instance v1, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    const/4 v3, 0x0

    invoke-direct {v1, p0, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;-><init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;Lcom/google/wireless/tacotruck/proto/Data$1;)V

    .line 38740
    .local v1, result:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38741
    .local v0, from_bitField0_:I
    const/4 v2, 0x0

    .line 38742
    .local v2, to_bitField0_:I
    and-int/lit8 v3, v0, 0x1

    const/4 v4, 0x1

    if-ne v3, v4, :cond_10

    .line 38743
    or-int/lit8 v2, v2, 0x1

    .line 38745
    :cond_10
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$51902(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 38746
    and-int/lit8 v3, v0, 0x2

    const/4 v4, 0x2

    if-ne v3, v4, :cond_1c

    .line 38747
    or-int/lit8 v2, v2, 0x2

    .line 38749
    :cond_1c
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52002(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 38750
    and-int/lit8 v3, v0, 0x4

    const/4 v4, 0x4

    if-ne v3, v4, :cond_28

    .line 38751
    or-int/lit8 v2, v2, 0x4

    .line 38753
    :cond_28
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52102(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 38754
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, 0x8

    const/16 v4, 0x8

    if-ne v3, v4, :cond_43

    .line 38755
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-static {v3}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v3

    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 38756
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, -0x9

    iput v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38758
    :cond_43
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52202(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;

    .line 38759
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, 0x10

    const/16 v4, 0x10

    if-ne v3, v4, :cond_5e

    .line 38760
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-static {v3}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v3

    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 38761
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, -0x11

    iput v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38763
    :cond_5e
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52302(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;

    .line 38764
    and-int/lit8 v3, v0, 0x20

    const/16 v4, 0x20

    if-ne v3, v4, :cond_6b

    .line 38765
    or-int/lit8 v2, v2, 0x8

    .line 38767
    :cond_6b
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52402(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 38768
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, 0x40

    const/16 v4, 0x40

    if-ne v3, v4, :cond_87

    .line 38769
    new-instance v3, Lcom/google/protobuf/UnmodifiableLazyStringList;

    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-direct {v3, v4}, Lcom/google/protobuf/UnmodifiableLazyStringList;-><init>(Lcom/google/protobuf/LazyStringList;)V

    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 38771
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, -0x41

    iput v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38773
    :cond_87
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52502(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/protobuf/LazyStringList;)Lcom/google/protobuf/LazyStringList;

    .line 38774
    and-int/lit16 v3, v0, 0x80

    const/16 v4, 0x80

    if-ne v3, v4, :cond_94

    .line 38775
    or-int/lit8 v2, v2, 0x10

    .line 38777
    :cond_94
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52602(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 38778
    and-int/lit16 v3, v0, 0x100

    const/16 v4, 0x100

    if-ne v3, v4, :cond_a1

    .line 38779
    or-int/lit8 v2, v2, 0x20

    .line 38781
    :cond_a1
    iget-boolean v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52702(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Z)Z

    .line 38782
    and-int/lit16 v3, v0, 0x200

    const/16 v4, 0x200

    if-ne v3, v4, :cond_ae

    .line 38783
    or-int/lit8 v2, v2, 0x40

    .line 38785
    :cond_ae
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52802(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 38786
    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I
    invoke-static {v1, v2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52902(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;I)I

    .line 38787
    return-object v1
.end method

.method public bridge synthetic clear()Lcom/google/protobuf/GeneratedMessageLite$Builder;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clear()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic clear()Lcom/google/protobuf/MessageLite$Builder;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clear()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public clear()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 38688
    invoke-super {p0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->clear()Lcom/google/protobuf/GeneratedMessageLite$Builder;

    .line 38689
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 38690
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x2

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38691
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 38692
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x3

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38693
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 38694
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x5

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38695
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 38696
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x9

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38697
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 38698
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x11

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38699
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 38700
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x21

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38701
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 38702
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x41

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38703
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 38704
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x81

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38705
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 38706
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x101

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38707
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 38708
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x201

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38709
    return-object p0
.end method

.method public clearActiveOccupant()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39114
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 39115
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x9

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39117
    return-object p0
.end method

.method public clearBroadcastId()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39377
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x201

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39378
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastId()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 39380
    return-object p0
.end method

.method public clearIdIsAutogenerated()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39346
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x101

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39347
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 39349
    return-object p0
.end method

.method public clearInactiveOccupant()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39203
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 39204
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x11

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39206
    return-object p0
.end method

.method public clearNotificationId()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39296
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 39297
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x41

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39299
    return-object p0
.end method

.method public clearRoomDomain()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39240
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x21

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39241
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomain()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 39243
    return-object p0
.end method

.method public clearRoomId()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 38954
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x2

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38955
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomId()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 38957
    return-object p0
.end method

.method public clearSubject()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39026
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x5

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39027
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubject()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 39029
    return-object p0
.end method

.method public clearType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 39325
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x81

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39326
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 39328
    return-object p0
.end method

.method public clearUrl()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 38990
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x3

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38991
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrl()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 38993
    return-object p0
.end method

.method public bridge synthetic clone()Lcom/google/protobuf/AbstractMessageLite$Builder;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic clone()Lcom/google/protobuf/GeneratedMessageLite$Builder;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3

    .prologue
    .line 38713
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v1

    invoke-virtual {v0, v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic clone()Ljava/lang/Object;
    .registers 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/lang/CloneNotSupportedException;
        }
    .end annotation

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public getActiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 39054
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getActiveOccupantCount()I
    .registers 2

    .prologue
    .line 39051
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getActiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 39048
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-static {v0}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public getBroadcastId()Ljava/lang/String;
    .registers 4

    .prologue
    .line 39358
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 39359
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 39360
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 39361
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 39364
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/GeneratedMessageLite;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 38672
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 2

    .prologue
    .line 38717
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getIdIsAutogenerated()Z
    .registers 2

    .prologue
    .line 39337
    iget-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    return v0
.end method

.method public getInactiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 39143
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getInactiveOccupantCount()I
    .registers 2

    .prologue
    .line 39140
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getInactiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 39137
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-static {v0}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public getNotificationId(I)Ljava/lang/String;
    .registers 3
    .parameter "index"

    .prologue
    .line 39267
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1}, Lcom/google/protobuf/LazyStringList;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/lang/String;

    return-object v0
.end method

.method public getNotificationIdCount()I
    .registers 2

    .prologue
    .line 39264
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v0

    return v0
.end method

.method public getNotificationIdList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .prologue
    .line 39261
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-static {v0}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public getRoomDomain()Ljava/lang/String;
    .registers 4

    .prologue
    .line 39221
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 39222
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 39223
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 39224
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 39227
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public getRoomId()Ljava/lang/String;
    .registers 4

    .prologue
    .line 38935
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 38936
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 38937
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 38938
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 38941
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public getSubject()Ljava/lang/String;
    .registers 4

    .prologue
    .line 39007
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 39008
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 39009
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 39010
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 39013
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public getType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    .registers 2

    .prologue
    .line 39313
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    return-object v0
.end method

.method public getUrl()Ljava/lang/String;
    .registers 4

    .prologue
    .line 38971
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 38972
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 38973
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 38974
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 38977
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public hasBroadcastId()Z
    .registers 3

    .prologue
    .line 39355
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, 0x200

    const/16 v1, 0x200

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIdIsAutogenerated()Z
    .registers 3

    .prologue
    .line 39334
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, 0x100

    const/16 v1, 0x100

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomDomain()Z
    .registers 3

    .prologue
    .line 39218
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x20

    const/16 v1, 0x20

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomId()Z
    .registers 3

    .prologue
    const/4 v0, 0x1

    .line 38932
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v0, :cond_8

    :goto_7
    return v0

    :cond_8
    const/4 v0, 0x0

    goto :goto_7
.end method

.method public hasSubject()Z
    .registers 3

    .prologue
    .line 39004
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x4

    const/4 v1, 0x4

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasType()Z
    .registers 3

    .prologue
    .line 39310
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, 0x80

    const/16 v1, 0x80

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasUrl()Z
    .registers 3

    .prologue
    .line 38968
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x2

    const/4 v1, 0x2

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public final isInitialized()Z
    .registers 2

    .prologue
    .line 38847
    const/4 v0, 0x1

    return v0
.end method

.method public bridge synthetic mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/protobuf/AbstractMessageLite$Builder;
    .registers 4
    .parameter "x0"
    .parameter "x1"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 38672
    invoke-virtual {p0, p1, p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic mergeFrom(Lcom/google/protobuf/GeneratedMessageLite;)Lcom/google/protobuf/GeneratedMessageLite$Builder;
    .registers 3
    .parameter "x0"

    .prologue
    .line 38672
    check-cast p1, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    .end local p1
    invoke-virtual {p0, p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/protobuf/MessageLite$Builder;
    .registers 4
    .parameter "x0"
    .parameter "x1"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 38672
    invoke-virtual {p0, p1, p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 9
    .parameter "input"
    .parameter "extensionRegistry"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 38855
    :cond_0
    :goto_0
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readTag()I

    move-result v2

    .line 38856
    .local v2, tag:I
    sparse-switch v2, :sswitch_data_9c

    .line 38861
    invoke-virtual {p0, p1, p2, v2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->parseUnknownField(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;I)Z

    move-result v4

    if-nez v4, :cond_0

    .line 38863
    :sswitch_d
    return-object p0

    .line 38868
    :sswitch_e
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x1

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38869
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    goto :goto_0

    .line 38873
    :sswitch_1b
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x2

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38874
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    goto :goto_0

    .line 38878
    :sswitch_28
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x4

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38879
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    goto :goto_0

    .line 38883
    :sswitch_35
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;

    move-result-object v1

    .line 38884
    .local v1, subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    invoke-virtual {p1, v1, p2}, Lcom/google/protobuf/CodedInputStream;->readMessage(Lcom/google/protobuf/MessageLite$Builder;Lcom/google/protobuf/ExtensionRegistryLite;)V

    .line 38885
    invoke-virtual {v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v4

    invoke-virtual {p0, v4}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->addActiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    goto :goto_0

    .line 38889
    .end local v1           #subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    :sswitch_44
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;

    move-result-object v1

    .line 38890
    .restart local v1       #subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    invoke-virtual {p1, v1, p2}, Lcom/google/protobuf/CodedInputStream;->readMessage(Lcom/google/protobuf/MessageLite$Builder;Lcom/google/protobuf/ExtensionRegistryLite;)V

    .line 38891
    invoke-virtual {v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v4

    invoke-virtual {p0, v4}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->addInactiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    goto :goto_0

    .line 38895
    .end local v1           #subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    :sswitch_53
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x20

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38896
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    goto :goto_0

    .line 38900
    :sswitch_60
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 38901
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-interface {v4, v5}, Lcom/google/protobuf/LazyStringList;->add(Lcom/google/protobuf/ByteString;)V

    goto :goto_0

    .line 38905
    :sswitch_6d
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readEnum()I

    move-result v0

    .line 38906
    .local v0, rawValue:I
    invoke-static {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->valueOf(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    move-result-object v3

    .line 38907
    .local v3, value:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    if-eqz v3, :cond_0

    .line 38908
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v4, v4, 0x80

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38909
    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    goto :goto_0

    .line 38914
    .end local v0           #rawValue:I
    .end local v3           #value:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    :sswitch_80
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v4, v4, 0x100

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38915
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBool()Z

    move-result v4

    iput-boolean v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    goto/16 :goto_0

    .line 38919
    :sswitch_8e
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v4, v4, 0x200

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38920
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    goto/16 :goto_0

    .line 38856
    :sswitch_data_9c
    .sparse-switch
        0x0 -> :sswitch_d
        0xa -> :sswitch_e
        0x12 -> :sswitch_1b
        0x1a -> :sswitch_28
        0x22 -> :sswitch_35
        0x2a -> :sswitch_44
        0x32 -> :sswitch_53
        0x3a -> :sswitch_60
        0x40 -> :sswitch_6d
        0x48 -> :sswitch_80
        0x52 -> :sswitch_8e
    .end sparse-switch
.end method

.method public mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "other"

    .prologue
    .line 38791
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    if-ne p1, v0, :cond_7

    .line 38843
    :cond_6
    :goto_6
    return-object p0

    .line 38792
    :cond_7
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasRoomId()Z

    move-result v0

    if-eqz v0, :cond_14

    .line 38793
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomId()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setRoomId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 38795
    :cond_14
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasUrl()Z

    move-result v0

    if-eqz v0, :cond_21

    .line 38796
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrl()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setUrl(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 38798
    :cond_21
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasSubject()Z

    move-result v0

    if-eqz v0, :cond_2e

    .line 38799
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubject()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setSubject(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 38801
    :cond_2e
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52200(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_4c

    .line 38802
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_be

    .line 38803
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52200(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 38804
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x9

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38811
    :cond_4c
    :goto_4c
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52300(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_6a

    .line 38812
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_cb

    .line 38813
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52300(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 38814
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x11

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38821
    :cond_6a
    :goto_6a
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasRoomDomain()Z

    move-result v0

    if-eqz v0, :cond_77

    .line 38822
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomain()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setRoomDomain(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 38824
    :cond_77
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52500(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;

    move-result-object v0

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_95

    .line 38825
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_d8

    .line 38826
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52500(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 38827
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x41

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38834
    :cond_95
    :goto_95
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasType()Z

    move-result v0

    if-eqz v0, :cond_a2

    .line 38835
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setType(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 38837
    :cond_a2
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasIdIsAutogenerated()Z

    move-result v0

    if-eqz v0, :cond_af

    .line 38838
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getIdIsAutogenerated()Z

    move-result v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setIdIsAutogenerated(Z)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 38840
    :cond_af
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasBroadcastId()Z

    move-result v0

    if-eqz v0, :cond_6

    .line 38841
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastId()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setBroadcastId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    goto/16 :goto_6

    .line 38806
    :cond_be
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 38807
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52200(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->addAll(Ljava/util/Collection;)Z

    goto :goto_4c

    .line 38816
    :cond_cb
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 38817
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52300(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->addAll(Ljava/util/Collection;)Z

    goto :goto_6a

    .line 38829
    :cond_d8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 38830
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$52500(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;

    move-result-object v1

    invoke-interface {v0, v1}, Lcom/google/protobuf/LazyStringList;->addAll(Ljava/util/Collection;)Z

    goto :goto_95
.end method

.method public setActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 39068
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39069
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 39071
    return-object p0
.end method

.method public setActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 39058
    if-nez p2, :cond_8

    .line 39059
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39061
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 39062
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 39064
    return-object p0
.end method

.method public setBroadcastId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39368
    if-nez p1, :cond_8

    .line 39369
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39371
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v0, v0, 0x200

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39372
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 39374
    return-object p0
.end method

.method public setIdIsAutogenerated(Z)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39340
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v0, v0, 0x100

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39341
    iput-boolean p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 39343
    return-object p0
.end method

.method public setInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 39157
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39158
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 39160
    return-object p0
.end method

.method public setInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 39147
    if-nez p2, :cond_8

    .line 39148
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39150
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 39151
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 39153
    return-object p0
.end method

.method public setNotificationId(ILjava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 39271
    if-nez p2, :cond_8

    .line 39272
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39274
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 39275
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1, p2}, Lcom/google/protobuf/LazyStringList;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 39277
    return-object p0
.end method

.method public setRoomDomain(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39231
    if-nez p1, :cond_8

    .line 39232
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39234
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x20

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39235
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 39237
    return-object p0
.end method

.method public setRoomId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 38945
    if-nez p1, :cond_8

    .line 38946
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 38948
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x1

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38949
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 38951
    return-object p0
.end method

.method public setSubject(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39017
    if-nez p1, :cond_8

    .line 39018
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39020
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x4

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39021
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 39023
    return-object p0
.end method

.method public setType(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 39316
    if-nez p1, :cond_8

    .line 39317
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 39319
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v0, v0, 0x80

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 39320
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 39322
    return-object p0
.end method

.method public setUrl(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 38981
    if-nez p1, :cond_8

    .line 38982
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 38984
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x2

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 38985
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 38987
    return-object p0
.end method
