.class public final Lcom/google/api/services/plusi/model/HangoutDataJson;
.super Lcom/google/android/apps/plus/json/EsJson;
.source "HangoutDataJson.java"


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lcom/google/android/apps/plus/json/EsJson",
        "<",
        "Lcom/google/api/services/plusi/model/HangoutData;",
        ">;"
    }
.end annotation


# static fields
.field static final INSTANCE:Lcom/google/api/services/plusi/model/HangoutDataJson;


# direct methods
.method static constructor <clinit>()V
    .registers 1

    .prologue
    .line 14
    new-instance v0, Lcom/google/api/services/plusi/model/HangoutDataJson;

    invoke-direct {v0}, Lcom/google/api/services/plusi/model/HangoutDataJson;-><init>()V

    sput-object v0, Lcom/google/api/services/plusi/model/HangoutDataJson;->INSTANCE:Lcom/google/api/services/plusi/model/HangoutDataJson;

    return-void
.end method

.method private constructor <init>()V
    .registers 5

    .prologue
    .line 21
    const-class v0, Lcom/google/api/services/plusi/model/HangoutData;

    const/16 v1, 0x19

    new-array v1, v1, [Ljava/lang/Object;

    const/4 v2, 0x0

    const-string v3, "idIsAutogenerated"

    aput-object v3, v1, v2

    const/4 v2, 0x1

    const-string v3, "isViewOnly"

    aput-object v3, v1, v2

    const/4 v2, 0x2

    const-string v3, "topic"

    aput-object v3, v1, v2

    const/4 v2, 0x3

    const-string v3, "roomId"

    aput-object v3, v1, v2

    const/4 v2, 0x4

    const-string v3, "subject"

    aput-object v3, v1, v2

    const/4 v2, 0x5

    const-string v3, "preferredLanguage"

    aput-object v3, v1, v2

    const/4 v2, 0x6

    const-string v3, "hashedRoomId"

    aput-object v3, v1, v2

    const/4 v2, 0x7

    const-string v3, "joinType"

    aput-object v3, v1, v2

    const/16 v2, 0x8

    const-string v3, "topicMaybeNsfw"

    aput-object v3, v1, v2

    const/16 v2, 0x9

    const-string v3, "type"

    aput-object v3, v1, v2

    const/16 v2, 0xa

    const-string v3, "topicUrl"

    aput-object v3, v1, v2

    const/16 v2, 0xb

    const-class v3, Lcom/google/api/services/plusi/model/HangoutOccupantJson;

    aput-object v3, v1, v2

    const/16 v2, 0xc

    const-string v3, "occupantEver"

    aput-object v3, v1, v2

    const/16 v2, 0xd

    const-class v3, Lcom/google/api/services/plusi/model/HangoutOccupantJson;

    aput-object v3, v1, v2

    const/16 v2, 0xe

    const-string v3, "occupant"

    aput-object v3, v1, v2

    const/16 v2, 0xf

    const-string v3, "broadcastTitle"

    aput-object v3, v1, v2

    const/16 v2, 0x10

    const-string v3, "notificationId"

    aput-object v3, v1, v2

    const/16 v2, 0x11

    const-class v3, Lcom/google/api/services/plusi/model/HangoutDataBroadcastDetailsJson;

    aput-object v3, v1, v2

    const/16 v2, 0x12

    const-string v3, "broadcastDetails"

    aput-object v3, v1, v2

    const/16 v2, 0x13

    const-string v3, "isActive"

    aput-object v3, v1, v2

    const/16 v2, 0x14

    const-string v3, "url"

    aput-object v3, v1, v2

    const/16 v2, 0x15

    const-string v3, "broadcastId"

    aput-object v3, v1, v2

    const/16 v2, 0x16

    const-string v3, "region"

    aput-object v3, v1, v2

    const/16 v2, 0x17

    const-string v3, "isNoMinors"

    aput-object v3, v1, v2

    const/16 v2, 0x18

    const-string v3, "roomDomain"

    aput-object v3, v1, v2

    invoke-direct {p0, v0, v1}, Lcom/google/android/apps/plus/json/EsJson;-><init>(Ljava/lang/Class;[Ljava/lang/Object;)V

    .line 44
    return-void
.end method

.method public static getInstance()Lcom/google/api/services/plusi/model/HangoutDataJson;
    .registers 1

    .prologue
    .line 17
    sget-object v0, Lcom/google/api/services/plusi/model/HangoutDataJson;->INSTANCE:Lcom/google/api/services/plusi/model/HangoutDataJson;

    return-object v0
.end method


# virtual methods
.method public getValues(Lcom/google/api/services/plusi/model/HangoutData;)[Ljava/lang/Object;
    .registers 5
    .parameter "object"

    .prologue
    .line 53
    const/16 v0, 0x16

    new-array v0, v0, [Ljava/lang/Object;

    const/4 v1, 0x0

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->idIsAutogenerated:Ljava/lang/Boolean;

    aput-object v2, v0, v1

    const/4 v1, 0x1

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->isViewOnly:Ljava/lang/Boolean;

    aput-object v2, v0, v1

    const/4 v1, 0x2

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->topic:Ljava/lang/String;

    aput-object v2, v0, v1

    const/4 v1, 0x3

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->roomId:Ljava/lang/String;

    aput-object v2, v0, v1

    const/4 v1, 0x4

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->subject:Ljava/lang/String;

    aput-object v2, v0, v1

    const/4 v1, 0x5

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->preferredLanguage:Ljava/lang/String;

    aput-object v2, v0, v1

    const/4 v1, 0x6

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->hashedRoomId:Ljava/lang/String;

    aput-object v2, v0, v1

    const/4 v1, 0x7

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->joinType:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0x8

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->topicMaybeNsfw:Ljava/lang/Boolean;

    aput-object v2, v0, v1

    const/16 v1, 0x9

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->type:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0xa

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->topicUrl:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0xb

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->occupantEver:Ljava/util/List;

    aput-object v2, v0, v1

    const/16 v1, 0xc

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->occupant:Ljava/util/List;

    aput-object v2, v0, v1

    const/16 v1, 0xd

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->broadcastTitle:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0xe

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->notificationId:Ljava/util/List;

    aput-object v2, v0, v1

    const/16 v1, 0xf

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->broadcastDetails:Lcom/google/api/services/plusi/model/HangoutDataBroadcastDetails;

    aput-object v2, v0, v1

    const/16 v1, 0x10

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->isActive:Ljava/lang/Boolean;

    aput-object v2, v0, v1

    const/16 v1, 0x11

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->url:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0x12

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->broadcastId:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0x13

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->region:Ljava/lang/String;

    aput-object v2, v0, v1

    const/16 v1, 0x14

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->isNoMinors:Ljava/lang/Boolean;

    aput-object v2, v0, v1

    const/16 v1, 0x15

    iget-object v2, p1, Lcom/google/api/services/plusi/model/HangoutData;->roomDomain:Ljava/lang/String;

    aput-object v2, v0, v1

    return-object v0
.end method

.method public bridge synthetic getValues(Ljava/lang/Object;)[Ljava/lang/Object;
    .registers 3
    .parameter "x0"

    .prologue
    .line 11
    check-cast p1, Lcom/google/api/services/plusi/model/HangoutData;

    .end local p1
    invoke-virtual {p0, p1}, Lcom/google/api/services/plusi/model/HangoutDataJson;->getValues(Lcom/google/api/services/plusi/model/HangoutData;)[Ljava/lang/Object;

    move-result-object v0

    return-object v0
.end method

.method public newInstance()Lcom/google/api/services/plusi/model/HangoutData;
    .registers 2

    .prologue
    .line 48
    new-instance v0, Lcom/google/api/services/plusi/model/HangoutData;

    invoke-direct {v0}, Lcom/google/api/services/plusi/model/HangoutData;-><init>()V

    return-object v0
.end method

.method public bridge synthetic newInstance()Ljava/lang/Object;
    .registers 2

    .prologue
    .line 11
    invoke-virtual {p0}, Lcom/google/api/services/plusi/model/HangoutDataJson;->newInstance()Lcom/google/api/services/plusi/model/HangoutData;

    move-result-object v0

    return-object v0
.end method
