.class public final Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
.super Lcom/google/protobuf/GeneratedMessageLite$Builder;
.source "Data.java"

# interfaces
.implements Lcom/google/wireless/tacotruck/proto/Data$HangoutDataOrBuilder;


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "Builder"
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lcom/google/protobuf/GeneratedMessageLite$Builder",
        "<",
        "Lcom/google/wireless/tacotruck/proto/Data$HangoutData;",
        "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;",
        ">;",
        "Lcom/google/wireless/tacotruck/proto/Data$HangoutDataOrBuilder;"
    }
.end annotation


# instance fields
.field private activeOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private bitField0_:I

.field private broadcastId_:Ljava/lang/Object;

.field private idIsAutogenerated_:Z

.field private inactiveOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private notificationId_:Lcom/google/protobuf/LazyStringList;

.field private roomDomain_:Ljava/lang/Object;

.field private roomId_:Ljava/lang/Object;

.field private subject_:Ljava/lang/Object;

.field private type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

.field private url_:Ljava/lang/Object;


# direct methods
.method private constructor <init>()V
    .registers 2

    .prologue
    .line 35896
    invoke-direct {p0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;-><init>()V

    .line 36149
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 36185
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 36221
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 36257
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 36346
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 36435
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 36471
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 36527
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 36551
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 36572
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 35897
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->maybeForceBuilderInitialization()V

    .line 35898
    return-void
.end method

.method static synthetic access$48100(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 2
    .parameter "x0"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/google/protobuf/InvalidProtocolBufferException;
        }
    .end annotation

    .prologue
    .line 35891
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildParsed()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method static synthetic access$48200()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 1

    .prologue
    .line 35891
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method private buildParsed()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 3
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/google/protobuf/InvalidProtocolBufferException;
        }
    .end annotation

    .prologue
    .line 35949
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    .line 35950
    .local v0, result:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->isInitialized()Z

    move-result v1

    if-nez v1, :cond_13

    .line 35951
    invoke-static {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->newUninitializedMessageException(Lcom/google/protobuf/MessageLite;)Lcom/google/protobuf/UninitializedMessageException;

    move-result-object v1

    invoke-virtual {v1}, Lcom/google/protobuf/UninitializedMessageException;->asInvalidProtocolBufferException()Lcom/google/protobuf/InvalidProtocolBufferException;

    move-result-object v1

    throw v1

    .line 35954
    :cond_13
    return-object v0
.end method

.method private static create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 1

    .prologue
    .line 35903
    new-instance v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    invoke-direct {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;-><init>()V

    return-object v0
.end method

.method private ensureActiveOccupantIsMutable()V
    .registers 3

    .prologue
    .line 36260
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x8

    const/16 v1, 0x8

    if-eq v0, v1, :cond_17

    .line 36261
    new-instance v0, Ljava/util/ArrayList;

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-direct {v0, v1}, Ljava/util/ArrayList;-><init>(Ljava/util/Collection;)V

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 36262
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x8

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36264
    :cond_17
    return-void
.end method

.method private ensureInactiveOccupantIsMutable()V
    .registers 3

    .prologue
    .line 36349
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x10

    const/16 v1, 0x10

    if-eq v0, v1, :cond_17

    .line 36350
    new-instance v0, Ljava/util/ArrayList;

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-direct {v0, v1}, Ljava/util/ArrayList;-><init>(Ljava/util/Collection;)V

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 36351
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x10

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36353
    :cond_17
    return-void
.end method

.method private ensureNotificationIdIsMutable()V
    .registers 3

    .prologue
    .line 36473
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x40

    const/16 v1, 0x40

    if-eq v0, v1, :cond_17

    .line 36474
    new-instance v0, Lcom/google/protobuf/LazyStringArrayList;

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-direct {v0, v1}, Lcom/google/protobuf/LazyStringArrayList;-><init>(Ljava/util/List;)V

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 36475
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x40

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36477
    :cond_17
    return-void
.end method

.method private maybeForceBuilderInitialization()V
    .registers 1

    .prologue
    .line 35901
    return-void
.end method


# virtual methods
.method public addActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 36320
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36321
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 36323
    return-object p0
.end method

.method public addActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 36303
    if-nez p2, :cond_8

    .line 36304
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36306
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36307
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 36309
    return-object p0
.end method

.method public addActiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "builderForValue"

    .prologue
    .line 36313
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36314
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 36316
    return-object p0
.end method

.method public addActiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36293
    if-nez p1, :cond_8

    .line 36294
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36296
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36297
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 36299
    return-object p0
.end method

.method public addAllActiveOccupant(Ljava/lang/Iterable;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Iterable",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;)",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;"
        }
    .end annotation

    .prologue
    .line 36327
    .local p1, values:Ljava/lang/Iterable;,"Ljava/lang/Iterable<+Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;>;"
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36328
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-static {p1, v0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->addAll(Ljava/lang/Iterable;Ljava/util/Collection;)V

    .line 36330
    return-object p0
.end method

.method public addAllInactiveOccupant(Ljava/lang/Iterable;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Iterable",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;)",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;"
        }
    .end annotation

    .prologue
    .line 36416
    .local p1, values:Ljava/lang/Iterable;,"Ljava/lang/Iterable<+Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;>;"
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36417
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-static {p1, v0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->addAll(Ljava/lang/Iterable;Ljava/util/Collection;)V

    .line 36419
    return-object p0
.end method

.method public addAllNotificationId(Ljava/lang/Iterable;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/Iterable",
            "<",
            "Ljava/lang/String;",
            ">;)",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;"
        }
    .end annotation

    .prologue
    .line 36509
    .local p1, values:Ljava/lang/Iterable;,"Ljava/lang/Iterable<Ljava/lang/String;>;"
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 36510
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-static {p1, v0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->addAll(Ljava/lang/Iterable;Ljava/util/Collection;)V

    .line 36512
    return-object p0
.end method

.method public addInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 36409
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36410
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 36412
    return-object p0
.end method

.method public addInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 36392
    if-nez p2, :cond_8

    .line 36393
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36395
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36396
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->add(ILjava/lang/Object;)V

    .line 36398
    return-object p0
.end method

.method public addInactiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "builderForValue"

    .prologue
    .line 36402
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36403
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 36405
    return-object p0
.end method

.method public addInactiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36382
    if-nez p1, :cond_8

    .line 36383
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36385
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36386
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 36388
    return-object p0
.end method

.method public addNotificationId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36499
    if-nez p1, :cond_8

    .line 36500
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36502
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 36503
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1}, Lcom/google/protobuf/LazyStringList;->add(Ljava/lang/Object;)Z

    .line 36505
    return-object p0
.end method

.method public build()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 3

    .prologue
    .line 35940
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    .line 35941
    .local v0, result:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->isInitialized()Z

    move-result v1

    if-nez v1, :cond_f

    .line 35942
    invoke-static {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->newUninitializedMessageException(Lcom/google/protobuf/MessageLite;)Lcom/google/protobuf/UninitializedMessageException;

    move-result-object v1

    throw v1

    .line 35944
    :cond_f
    return-object v0
.end method

.method public bridge synthetic buildPartial()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 6

    .prologue
    .line 35958
    new-instance v1, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    const/4 v3, 0x0

    invoke-direct {v1, p0, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;-><init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;Lcom/google/wireless/tacotruck/proto/Data$1;)V

    .line 35959
    .local v1, result:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35960
    .local v0, from_bitField0_:I
    const/4 v2, 0x0

    .line 35961
    .local v2, to_bitField0_:I
    and-int/lit8 v3, v0, 0x1

    const/4 v4, 0x1

    if-ne v3, v4, :cond_10

    .line 35962
    or-int/lit8 v2, v2, 0x1

    .line 35964
    :cond_10
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48402(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 35965
    and-int/lit8 v3, v0, 0x2

    const/4 v4, 0x2

    if-ne v3, v4, :cond_1c

    .line 35966
    or-int/lit8 v2, v2, 0x2

    .line 35968
    :cond_1c
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48502(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 35969
    and-int/lit8 v3, v0, 0x4

    const/4 v4, 0x4

    if-ne v3, v4, :cond_28

    .line 35970
    or-int/lit8 v2, v2, 0x4

    .line 35972
    :cond_28
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48602(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 35973
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, 0x8

    const/16 v4, 0x8

    if-ne v3, v4, :cond_43

    .line 35974
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-static {v3}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v3

    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 35975
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, -0x9

    iput v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35977
    :cond_43
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48702(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;

    .line 35978
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, 0x10

    const/16 v4, 0x10

    if-ne v3, v4, :cond_5e

    .line 35979
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-static {v3}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v3

    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 35980
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, -0x11

    iput v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35982
    :cond_5e
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48802(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;

    .line 35983
    and-int/lit8 v3, v0, 0x20

    const/16 v4, 0x20

    if-ne v3, v4, :cond_6b

    .line 35984
    or-int/lit8 v2, v2, 0x8

    .line 35986
    :cond_6b
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48902(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 35987
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, 0x40

    const/16 v4, 0x40

    if-ne v3, v4, :cond_87

    .line 35988
    new-instance v3, Lcom/google/protobuf/UnmodifiableLazyStringList;

    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-direct {v3, v4}, Lcom/google/protobuf/UnmodifiableLazyStringList;-><init>(Lcom/google/protobuf/LazyStringList;)V

    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 35990
    iget v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v3, v3, -0x41

    iput v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35992
    :cond_87
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49002(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/protobuf/LazyStringList;)Lcom/google/protobuf/LazyStringList;

    .line 35993
    and-int/lit16 v3, v0, 0x80

    const/16 v4, 0x80

    if-ne v3, v4, :cond_94

    .line 35994
    or-int/lit8 v2, v2, 0x10

    .line 35996
    :cond_94
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49102(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 35997
    and-int/lit16 v3, v0, 0x100

    const/16 v4, 0x100

    if-ne v3, v4, :cond_a1

    .line 35998
    or-int/lit8 v2, v2, 0x20

    .line 36000
    :cond_a1
    iget-boolean v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49202(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Z)Z

    .line 36001
    and-int/lit16 v3, v0, 0x200

    const/16 v4, 0x200

    if-ne v3, v4, :cond_ae

    .line 36002
    or-int/lit8 v2, v2, 0x40

    .line 36004
    :cond_ae
    iget-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;
    invoke-static {v1, v3}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49302(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;

    .line 36005
    #setter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I
    invoke-static {v1, v2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49402(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;I)I

    .line 36006
    return-object v1
.end method

.method public bridge synthetic clear()Lcom/google/protobuf/GeneratedMessageLite$Builder;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clear()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic clear()Lcom/google/protobuf/MessageLite$Builder;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clear()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public clear()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 35907
    invoke-super {p0}, Lcom/google/protobuf/GeneratedMessageLite$Builder;->clear()Lcom/google/protobuf/GeneratedMessageLite$Builder;

    .line 35908
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 35909
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x2

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35910
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 35911
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x3

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35912
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 35913
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x5

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35914
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 35915
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x9

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35916
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 35917
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x11

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35918
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 35919
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x21

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35920
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 35921
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x41

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35922
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 35923
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x81

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35924
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 35925
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x101

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35926
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 35927
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x201

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 35928
    return-object p0
.end method

.method public clearActiveOccupant()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36333
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 36334
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x9

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36336
    return-object p0
.end method

.method public clearBroadcastId()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36596
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x201

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36597
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastId()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 36599
    return-object p0
.end method

.method public clearIdIsAutogenerated()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36565
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x101

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36566
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 36568
    return-object p0
.end method

.method public clearInactiveOccupant()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36422
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 36423
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x11

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36425
    return-object p0
.end method

.method public clearNotificationId()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36515
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 36516
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x41

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36518
    return-object p0
.end method

.method public clearRoomDomain()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36459
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x21

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36460
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomain()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 36462
    return-object p0
.end method

.method public clearRoomId()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36173
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x2

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36174
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomId()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 36176
    return-object p0
.end method

.method public clearSubject()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36245
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x5

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36246
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubject()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 36248
    return-object p0
.end method

.method public clearType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36544
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, -0x81

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36545
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 36547
    return-object p0
.end method

.method public clearUrl()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2

    .prologue
    .line 36209
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x3

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36210
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    invoke-virtual {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrl()Ljava/lang/String;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 36212
    return-object p0
.end method

.method public bridge synthetic clone()Lcom/google/protobuf/AbstractMessageLite$Builder;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic clone()Lcom/google/protobuf/GeneratedMessageLite$Builder;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3

    .prologue
    .line 35932
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v1

    invoke-virtual {v0, v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic clone()Ljava/lang/Object;
    .registers 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/lang/CloneNotSupportedException;
        }
    .end annotation

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->clone()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public getActiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 36273
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getActiveOccupantCount()I
    .registers 2

    .prologue
    .line 36270
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getActiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 36267
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-static {v0}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public getBroadcastId()Ljava/lang/String;
    .registers 4

    .prologue
    .line 36577
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 36578
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 36579
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 36580
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 36583
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/GeneratedMessageLite;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 35891
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 2

    .prologue
    .line 35936
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getIdIsAutogenerated()Z
    .registers 2

    .prologue
    .line 36556
    iget-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    return v0
.end method

.method public getInactiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 36362
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getInactiveOccupantCount()I
    .registers 2

    .prologue
    .line 36359
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getInactiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 36356
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-static {v0}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public getNotificationId(I)Ljava/lang/String;
    .registers 3
    .parameter "index"

    .prologue
    .line 36486
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1}, Lcom/google/protobuf/LazyStringList;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/lang/String;

    return-object v0
.end method

.method public getNotificationIdCount()I
    .registers 2

    .prologue
    .line 36483
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v0

    return v0
.end method

.method public getNotificationIdList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .prologue
    .line 36480
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-static {v0}, Ljava/util/Collections;->unmodifiableList(Ljava/util/List;)Ljava/util/List;

    move-result-object v0

    return-object v0
.end method

.method public getRoomDomain()Ljava/lang/String;
    .registers 4

    .prologue
    .line 36440
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 36441
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 36442
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 36443
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 36446
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public getRoomId()Ljava/lang/String;
    .registers 4

    .prologue
    .line 36154
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 36155
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 36156
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 36157
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 36160
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public getSubject()Ljava/lang/String;
    .registers 4

    .prologue
    .line 36226
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 36227
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 36228
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 36229
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 36232
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public getType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    .registers 2

    .prologue
    .line 36532
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    return-object v0
.end method

.method public getUrl()Ljava/lang/String;
    .registers 4

    .prologue
    .line 36190
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 36191
    .local v0, ref:Ljava/lang/Object;
    instance-of v2, v0, Ljava/lang/String;

    if-nez v2, :cond_f

    .line 36192
    check-cast v0, Lcom/google/protobuf/ByteString;

    .end local v0           #ref:Ljava/lang/Object;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v1

    .line 36193
    .local v1, s:Ljava/lang/String;
    iput-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 36196
    .end local v1           #s:Ljava/lang/String;
    :goto_e
    return-object v1

    .restart local v0       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v0, Ljava/lang/String;

    .end local v0           #ref:Ljava/lang/Object;
    move-object v1, v0

    goto :goto_e
.end method

.method public hasBroadcastId()Z
    .registers 3

    .prologue
    .line 36574
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, 0x200

    const/16 v1, 0x200

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIdIsAutogenerated()Z
    .registers 3

    .prologue
    .line 36553
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, 0x100

    const/16 v1, 0x100

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomDomain()Z
    .registers 3

    .prologue
    .line 36437
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x20

    const/16 v1, 0x20

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomId()Z
    .registers 3

    .prologue
    const/4 v0, 0x1

    .line 36151
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v0, :cond_8

    :goto_7
    return v0

    :cond_8
    const/4 v0, 0x0

    goto :goto_7
.end method

.method public hasSubject()Z
    .registers 3

    .prologue
    .line 36223
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x4

    const/4 v1, 0x4

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasType()Z
    .registers 3

    .prologue
    .line 36529
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit16 v0, v0, 0x80

    const/16 v1, 0x80

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasUrl()Z
    .registers 3

    .prologue
    .line 36187
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, 0x2

    const/4 v1, 0x2

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public bridge synthetic mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/protobuf/AbstractMessageLite$Builder;
    .registers 4
    .parameter "x0"
    .parameter "x1"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 35891
    invoke-virtual {p0, p1, p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/protobuf/MessageLite$Builder;
    .registers 4
    .parameter "x0"
    .parameter "x1"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 35891
    invoke-virtual {p0, p1, p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public mergeFrom(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 9
    .parameter "input"
    .parameter "extensionRegistry"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 36074
    :cond_0
    :goto_0
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readTag()I

    move-result v2

    .line 36075
    .local v2, tag:I
    sparse-switch v2, :sswitch_data_9c

    .line 36080
    invoke-virtual {p0, p1, p2, v2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->parseUnknownField(Lcom/google/protobuf/CodedInputStream;Lcom/google/protobuf/ExtensionRegistryLite;I)Z

    move-result v4

    if-nez v4, :cond_0

    .line 36082
    :sswitch_d
    return-object p0

    .line 36087
    :sswitch_e
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x1

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36088
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    goto :goto_0

    .line 36092
    :sswitch_1b
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x2

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36093
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    goto :goto_0

    .line 36097
    :sswitch_28
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x4

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36098
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    goto :goto_0

    .line 36102
    :sswitch_35
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;

    move-result-object v1

    .line 36103
    .local v1, subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    invoke-virtual {p1, v1, p2}, Lcom/google/protobuf/CodedInputStream;->readMessage(Lcom/google/protobuf/MessageLite$Builder;Lcom/google/protobuf/ExtensionRegistryLite;)V

    .line 36104
    invoke-virtual {v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v4

    invoke-virtual {p0, v4}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->addActiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    goto :goto_0

    .line 36108
    .end local v1           #subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    :sswitch_44
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;

    move-result-object v1

    .line 36109
    .restart local v1       #subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    invoke-virtual {p1, v1, p2}, Lcom/google/protobuf/CodedInputStream;->readMessage(Lcom/google/protobuf/MessageLite$Builder;Lcom/google/protobuf/ExtensionRegistryLite;)V

    .line 36110
    invoke-virtual {v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->buildPartial()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v4

    invoke-virtual {p0, v4}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->addInactiveOccupant(Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    goto :goto_0

    .line 36114
    .end local v1           #subBuilder:Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;
    :sswitch_53
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v4, v4, 0x20

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36115
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    goto :goto_0

    .line 36119
    :sswitch_60
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 36120
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-interface {v4, v5}, Lcom/google/protobuf/LazyStringList;->add(Lcom/google/protobuf/ByteString;)V

    goto :goto_0

    .line 36124
    :sswitch_6d
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readEnum()I

    move-result v0

    .line 36125
    .local v0, rawValue:I
    invoke-static {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->valueOf(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    move-result-object v3

    .line 36126
    .local v3, value:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    if-eqz v3, :cond_0

    .line 36127
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v4, v4, 0x80

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36128
    iput-object v3, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    goto :goto_0

    .line 36133
    .end local v0           #rawValue:I
    .end local v3           #value:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    :sswitch_80
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v4, v4, 0x100

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36134
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBool()Z

    move-result v4

    iput-boolean v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    goto/16 :goto_0

    .line 36138
    :sswitch_8e
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v4, v4, 0x200

    iput v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36139
    invoke-virtual {p1}, Lcom/google/protobuf/CodedInputStream;->readBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    iput-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    goto/16 :goto_0

    .line 36075
    :sswitch_data_9c
    .sparse-switch
        0x0 -> :sswitch_d
        0xa -> :sswitch_e
        0x12 -> :sswitch_1b
        0x1a -> :sswitch_28
        0x22 -> :sswitch_35
        0x2a -> :sswitch_44
        0x32 -> :sswitch_53
        0x3a -> :sswitch_60
        0x40 -> :sswitch_6d
        0x48 -> :sswitch_80
        0x52 -> :sswitch_8e
    .end sparse-switch
.end method

.method public mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "other"

    .prologue
    .line 36010
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    if-ne p1, v0, :cond_7

    .line 36062
    :cond_6
    :goto_6
    return-object p0

    .line 36011
    :cond_7
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasRoomId()Z

    move-result v0

    if-eqz v0, :cond_14

    .line 36012
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomId()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setRoomId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 36014
    :cond_14
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasUrl()Z

    move-result v0

    if-eqz v0, :cond_21

    .line 36015
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrl()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setUrl(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 36017
    :cond_21
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasSubject()Z

    move-result v0

    if-eqz v0, :cond_2e

    .line 36018
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubject()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setSubject(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 36020
    :cond_2e
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48700(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_4c

    .line 36021
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_be

    .line 36022
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48700(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    .line 36023
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x9

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36030
    :cond_4c
    :goto_4c
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48800(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_6a

    .line 36031
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_cb

    .line 36032
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48800(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    .line 36033
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x11

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36040
    :cond_6a
    :goto_6a
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasRoomDomain()Z

    move-result v0

    if-eqz v0, :cond_77

    .line 36041
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomain()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setRoomDomain(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 36043
    :cond_77
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49000(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;

    move-result-object v0

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_95

    .line 36044
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_d8

    .line 36045
    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49000(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 36046
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    and-int/lit8 v0, v0, -0x41

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36053
    :cond_95
    :goto_95
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasType()Z

    move-result v0

    if-eqz v0, :cond_a2

    .line 36054
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setType(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 36056
    :cond_a2
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasIdIsAutogenerated()Z

    move-result v0

    if-eqz v0, :cond_af

    .line 36057
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getIdIsAutogenerated()Z

    move-result v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setIdIsAutogenerated(Z)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    .line 36059
    :cond_af
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->hasBroadcastId()Z

    move-result v0

    if-eqz v0, :cond_6

    .line 36060
    invoke-virtual {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastId()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->setBroadcastId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    goto/16 :goto_6

    .line 36025
    :cond_be
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36026
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48700(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->addAll(Ljava/util/Collection;)Z

    goto :goto_4c

    .line 36035
    :cond_cb
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36036
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$48800(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;

    move-result-object v1

    invoke-interface {v0, v1}, Ljava/util/List;->addAll(Ljava/util/Collection;)Z

    goto :goto_6a

    .line 36048
    :cond_d8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 36049
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    #getter for: Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;
    invoke-static {p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->access$49000(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;

    move-result-object v1

    invoke-interface {v0, v1}, Lcom/google/protobuf/LazyStringList;->addAll(Ljava/util/Collection;)Z

    goto :goto_95
.end method

.method public setActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 36287
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36288
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 36290
    return-object p0
.end method

.method public setActiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 36277
    if-nez p2, :cond_8

    .line 36278
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36280
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureActiveOccupantIsMutable()V

    .line 36281
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 36283
    return-object p0
.end method

.method public setBroadcastId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36587
    if-nez p1, :cond_8

    .line 36588
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36590
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v0, v0, 0x200

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36591
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->broadcastId_:Ljava/lang/Object;

    .line 36593
    return-object p0
.end method

.method public setIdIsAutogenerated(Z)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36559
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v0, v0, 0x100

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36560
    iput-boolean p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->idIsAutogenerated_:Z

    .line 36562
    return-object p0
.end method

.method public setInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 5
    .parameter "index"
    .parameter "builderForValue"

    .prologue
    .line 36376
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36377
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-virtual {p2}, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant$Builder;->build()Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    move-result-object v1

    invoke-interface {v0, p1, v1}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 36379
    return-object p0
.end method

.method public setInactiveOccupant(ILcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 36366
    if-nez p2, :cond_8

    .line 36367
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36369
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureInactiveOccupantIsMutable()V

    .line 36370
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1, p2}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 36372
    return-object p0
.end method

.method public setNotificationId(ILjava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 4
    .parameter "index"
    .parameter "value"

    .prologue
    .line 36490
    if-nez p2, :cond_8

    .line 36491
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36493
    :cond_8
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->ensureNotificationIdIsMutable()V

    .line 36494
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1, p2}, Lcom/google/protobuf/LazyStringList;->set(ILjava/lang/Object;)Ljava/lang/Object;

    .line 36496
    return-object p0
.end method

.method public setRoomDomain(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36450
    if-nez p1, :cond_8

    .line 36451
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36453
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x20

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36454
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomDomain_:Ljava/lang/Object;

    .line 36456
    return-object p0
.end method

.method public setRoomId(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36164
    if-nez p1, :cond_8

    .line 36165
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36167
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x1

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36168
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->roomId_:Ljava/lang/Object;

    .line 36170
    return-object p0
.end method

.method public setSubject(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36236
    if-nez p1, :cond_8

    .line 36237
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36239
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x4

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36240
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->subject_:Ljava/lang/Object;

    .line 36242
    return-object p0
.end method

.method public setType(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36535
    if-nez p1, :cond_8

    .line 36536
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36538
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit16 v0, v0, 0x80

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36539
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 36541
    return-object p0
.end method

.method public setUrl(Ljava/lang/String;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 3
    .parameter "value"

    .prologue
    .line 36200
    if-nez p1, :cond_8

    .line 36201
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0

    .line 36203
    :cond_8
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    or-int/lit8 v0, v0, 0x2

    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->bitField0_:I

    .line 36204
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->url_:Ljava/lang/Object;

    .line 36206
    return-object p0
.end method
