.class public final Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
.super Lcom/google/protobuf/GeneratedMessageLite;
.source "Data.java"

# interfaces
.implements Lcom/google/wireless/tacotruck/proto/Data$HangoutDataOrBuilder;


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/google/wireless/tacotruck/proto/Data;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "HangoutData"
.end annotation

.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;,
        Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    }
.end annotation


# static fields
.field private static final defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

.field private static final serialVersionUID:J


# instance fields
.field private activeOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private bitField0_:I

.field private broadcastId_:Ljava/lang/Object;

.field private idIsAutogenerated_:Z

.field private inactiveOccupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private memoizedIsInitialized:B

.field private memoizedSerializedSize:I

.field private notificationId_:Lcom/google/protobuf/LazyStringList;

.field private roomDomain_:Ljava/lang/Object;

.field private roomId_:Ljava/lang/Object;

.field private subject_:Ljava/lang/Object;

.field private type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

.field private url_:Ljava/lang/Object;


# direct methods
.method static constructor <clinit>()V
    .registers 2

    .prologue
    .line 36611
    new-instance v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    const/4 v1, 0x1

    invoke-direct {v0, v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;-><init>(Z)V

    sput-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    .line 36612
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    invoke-direct {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->initFields()V

    .line 36613
    return-void
.end method

.method private constructor <init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;)V
    .registers 3
    .parameter "builder"

    .prologue
    const/4 v0, -0x1

    .line 35408
    invoke-direct {p0, p1}, Lcom/google/protobuf/GeneratedMessageLite;-><init>(Lcom/google/protobuf/GeneratedMessageLite$Builder;)V

    .line 35711
    iput-byte v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    .line 35755
    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    .line 35409
    return-void
.end method

.method synthetic constructor <init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;Lcom/google/wireless/tacotruck/proto/Data$1;)V
    .registers 3
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    invoke-direct {p0, p1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;-><init>(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;)V

    return-void
.end method

.method private constructor <init>(Z)V
    .registers 3
    .parameter "noInit"

    .prologue
    const/4 v0, -0x1

    .line 35410
    invoke-direct {p0}, Lcom/google/protobuf/GeneratedMessageLite;-><init>()V

    .line 35711
    iput-byte v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    .line 35755
    iput v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    .line 35410
    return-void
.end method

.method static synthetic access$48402(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$48502(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$48602(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$48700(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;
    .registers 2
    .parameter "x0"

    .prologue
    .line 35403
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object v0
.end method

.method static synthetic access$48702(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object p1
.end method

.method static synthetic access$48800(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Ljava/util/List;
    .registers 2
    .parameter "x0"

    .prologue
    .line 35403
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object v0
.end method

.method static synthetic access$48802(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/util/List;)Ljava/util/List;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object p1
.end method

.method static synthetic access$48902(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$49000(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/protobuf/LazyStringList;
    .registers 2
    .parameter "x0"

    .prologue
    .line 35403
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object v0
.end method

.method static synthetic access$49002(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/protobuf/LazyStringList;)Lcom/google/protobuf/LazyStringList;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object p1
.end method

.method static synthetic access$49102(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    return-object p1
.end method

.method static synthetic access$49202(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-boolean p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    return p1
.end method

.method static synthetic access$49302(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput-object p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$49402(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;I)I
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 35403
    iput p1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    return p1
.end method

.method private getBroadcastIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 35688
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 35689
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 35690
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 35692
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 35695
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method public static getDefaultInstance()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 1

    .prologue
    .line 35414
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    return-object v0
.end method

.method private getRoomDomainBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 35622
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 35623
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 35624
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 35626
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 35629
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getRoomIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 35484
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 35485
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 35486
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 35488
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 35491
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getSubjectBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 35548
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 35549
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 35550
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 35552
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 35555
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getUrlBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 35516
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 35517
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 35518
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 35520
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 35523
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private initFields()V
    .registers 2

    .prologue
    .line 35700
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 35701
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 35702
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 35703
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    .line 35704
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    .line 35705
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 35706
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 35707
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->CONSUMER:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    .line 35708
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    .line 35709
    const-string v0, ""

    iput-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 35710
    return-void
.end method

.method public static newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 1

    .prologue
    .line 35884
    #calls: Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->create()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->access$48200()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public static newBuilder(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;
    .registers 2
    .parameter "prototype"

    .prologue
    .line 35887
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {v0, p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom(Lcom/google/wireless/tacotruck/proto/Data$HangoutData;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public static parseFrom([B)Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 2
    .parameter "data"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/google/protobuf/InvalidProtocolBufferException;
        }
    .end annotation

    .prologue
    .line 35831
    invoke-static {}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->newBuilder()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {v0, p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->mergeFrom([B)Lcom/google/protobuf/AbstractMessageLite$Builder;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;

    #calls: Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->buildParsed()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    invoke-static {v0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;->access$48100(Lcom/google/wireless/tacotruck/proto/Data$HangoutData$Builder;)Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method


# virtual methods
.method public getActiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 35573
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getActiveOccupantCount()I
    .registers 2

    .prologue
    .line 35570
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getActiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 35563
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getActiveOccupantOrBuilder(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;
    .registers 3
    .parameter "index"

    .prologue
    .line 35577
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;

    return-object v0
.end method

.method public getActiveOccupantOrBuilderList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;",
            ">;"
        }
    .end annotation

    .prologue
    .line 35567
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getBroadcastId()Ljava/lang/String;
    .registers 5

    .prologue
    .line 35674
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 35675
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 35676
    check-cast v1, Ljava/lang/String;

    .line 35684
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 35678
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 35680
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 35681
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 35682
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->broadcastId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 35684
    goto :goto_8
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 35403
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getDefaultInstanceForType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData;
    .registers 2

    .prologue
    .line 35418
    sget-object v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->defaultInstance:Lcom/google/wireless/tacotruck/proto/Data$HangoutData;

    return-object v0
.end method

.method public getIdIsAutogenerated()Z
    .registers 2

    .prologue
    .line 35664
    iget-boolean v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    return v0
.end method

.method public getInactiveOccupant(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 35594
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;

    return-object v0
.end method

.method public getInactiveOccupantCount()I
    .registers 2

    .prologue
    .line 35591
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getInactiveOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 35584
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getInactiveOccupantOrBuilder(I)Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;
    .registers 3
    .parameter "index"

    .prologue
    .line 35598
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;

    return-object v0
.end method

.method public getInactiveOccupantOrBuilderList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<+",
            "Lcom/google/wireless/tacotruck/proto/Data$HangoutOccupantOrBuilder;",
            ">;"
        }
    .end annotation

    .prologue
    .line 35588
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    return-object v0
.end method

.method public getNotificationId(I)Ljava/lang/String;
    .registers 3
    .parameter "index"

    .prologue
    .line 35644
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0, p1}, Lcom/google/protobuf/LazyStringList;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljava/lang/String;

    return-object v0
.end method

.method public getNotificationIdCount()I
    .registers 2

    .prologue
    .line 35641
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v0}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v0

    return v0
.end method

.method public getNotificationIdList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .prologue
    .line 35638
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object v0
.end method

.method public getRoomDomain()Ljava/lang/String;
    .registers 5

    .prologue
    .line 35608
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 35609
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 35610
    check-cast v1, Ljava/lang/String;

    .line 35618
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 35612
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 35614
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 35615
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 35616
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomDomain_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 35618
    goto :goto_8
.end method

.method public getRoomId()Ljava/lang/String;
    .registers 5

    .prologue
    .line 35470
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    .line 35471
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 35472
    check-cast v1, Ljava/lang/String;

    .line 35480
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 35474
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 35476
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 35477
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 35478
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->roomId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 35480
    goto :goto_8
.end method

.method public getSerializedSize()I
    .registers 10

    .prologue
    const/16 v8, 0x8

    const/4 v7, 0x4

    const/4 v6, 0x2

    const/4 v5, 0x1

    .line 35757
    iget v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    .line 35758
    .local v2, size:I
    const/4 v4, -0x1

    if-eq v2, v4, :cond_c

    move v3, v2

    .line 35807
    .end local v2           #size:I
    .local v3, size:I
    :goto_b
    return v3

    .line 35760
    .end local v3           #size:I
    .restart local v2       #size:I
    :cond_c
    const/4 v2, 0x0

    .line 35761
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x1

    if-ne v4, v5, :cond_1c

    .line 35762
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v5, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35765
    :cond_1c
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x2

    if-ne v4, v6, :cond_2b

    .line 35766
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v6, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35769
    :cond_2b
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x4

    if-ne v4, v7, :cond_3b

    .line 35770
    const/4 v4, 0x3

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubjectBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35773
    :cond_3b
    const/4 v1, 0x0

    .local v1, i:I
    :goto_3c
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    if-ge v1, v4, :cond_54

    .line 35774
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v4, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lcom/google/protobuf/MessageLite;

    invoke-static {v7, v4}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35773
    add-int/lit8 v1, v1, 0x1

    goto :goto_3c

    .line 35777
    :cond_54
    const/4 v1, 0x0

    :goto_55
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    if-ge v1, v4, :cond_6e

    .line 35778
    const/4 v5, 0x5

    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v4, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lcom/google/protobuf/MessageLite;

    invoke-static {v5, v4}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35777
    add-int/lit8 v1, v1, 0x1

    goto :goto_55

    .line 35781
    :cond_6e
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x8

    if-ne v4, v8, :cond_7e

    .line 35782
    const/4 v4, 0x6

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomainBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35786
    :cond_7e
    const/4 v0, 0x0

    .line 35787
    .local v0, dataSize:I
    const/4 v1, 0x0

    :goto_80
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v4}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v4

    if-ge v1, v4, :cond_96

    .line 35788
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v4, v1}, Lcom/google/protobuf/LazyStringList;->getByteString(I)Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSizeNoTag(Lcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v0, v4

    .line 35787
    add-int/lit8 v1, v1, 0x1

    goto :goto_80

    .line 35791
    :cond_96
    add-int/2addr v2, v0

    .line 35792
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getNotificationIdList()Ljava/util/List;

    move-result-object v4

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    mul-int/lit8 v4, v4, 0x1

    add-int/2addr v2, v4

    .line 35794
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x10

    const/16 v5, 0x10

    if-ne v4, v5, :cond_b5

    .line 35795
    iget-object v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    invoke-virtual {v4}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->getNumber()I

    move-result v4

    invoke-static {v8, v4}, Lcom/google/protobuf/CodedOutputStream;->computeEnumSize(II)I

    move-result v4

    add-int/2addr v2, v4

    .line 35798
    :cond_b5
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x20

    const/16 v5, 0x20

    if-ne v4, v5, :cond_c6

    .line 35799
    const/16 v4, 0x9

    iget-boolean v5, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 35802
    :cond_c6
    iget v4, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x40

    const/16 v5, 0x40

    if-ne v4, v5, :cond_d9

    .line 35803
    const/16 v4, 0xa

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 35806
    :cond_d9
    iput v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedSerializedSize:I

    move v3, v2

    .line 35807
    .end local v2           #size:I
    .restart local v3       #size:I
    goto/16 :goto_b
.end method

.method public getSubject()Ljava/lang/String;
    .registers 5

    .prologue
    .line 35534
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    .line 35535
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 35536
    check-cast v1, Ljava/lang/String;

    .line 35544
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 35538
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 35540
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 35541
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 35542
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->subject_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 35544
    goto :goto_8
.end method

.method public getType()Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;
    .registers 2

    .prologue
    .line 35654
    iget-object v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    return-object v0
.end method

.method public getUrl()Ljava/lang/String;
    .registers 5

    .prologue
    .line 35502
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    .line 35503
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 35504
    check-cast v1, Ljava/lang/String;

    .line 35512
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 35506
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 35508
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 35509
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 35510
    iput-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->url_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 35512
    goto :goto_8
.end method

.method public hasBroadcastId()Z
    .registers 3

    .prologue
    .line 35671
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x40

    const/16 v1, 0x40

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIdIsAutogenerated()Z
    .registers 3

    .prologue
    .line 35661
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x20

    const/16 v1, 0x20

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomDomain()Z
    .registers 3

    .prologue
    .line 35605
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x8

    const/16 v1, 0x8

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomId()Z
    .registers 3

    .prologue
    const/4 v0, 0x1

    .line 35467
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v0, :cond_8

    :goto_7
    return v0

    :cond_8
    const/4 v0, 0x0

    goto :goto_7
.end method

.method public hasSubject()Z
    .registers 3

    .prologue
    .line 35531
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x4

    const/4 v1, 0x4

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasType()Z
    .registers 3

    .prologue
    .line 35651
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x10

    const/16 v1, 0x10

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasUrl()Z
    .registers 3

    .prologue
    .line 35499
    iget v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x2

    const/4 v1, 0x2

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public final isInitialized()Z
    .registers 4

    .prologue
    const/4 v1, 0x1

    .line 35713
    iget-byte v0, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    .line 35714
    .local v0, isInitialized:B
    const/4 v2, -0x1

    if-eq v0, v2, :cond_b

    if-ne v0, v1, :cond_9

    .line 35717
    :goto_8
    return v1

    .line 35714
    :cond_9
    const/4 v1, 0x0

    goto :goto_8

    .line 35716
    :cond_b
    iput-byte v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->memoizedIsInitialized:B

    goto :goto_8
.end method

.method protected writeReplace()Ljava/lang/Object;
    .registers 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/ObjectStreamException;
        }
    .end annotation

    .prologue
    .line 35814
    invoke-super {p0}, Lcom/google/protobuf/GeneratedMessageLite;->writeReplace()Ljava/lang/Object;

    move-result-object v0

    return-object v0
.end method

.method public writeTo(Lcom/google/protobuf/CodedOutputStream;)V
    .registers 8
    .parameter "output"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    const/16 v5, 0x8

    const/4 v4, 0x4

    const/4 v3, 0x2

    const/4 v2, 0x1

    .line 35722
    invoke-virtual {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSerializedSize()I

    .line 35723
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v2, :cond_15

    .line 35724
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v2, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 35726
    :cond_15
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x2

    if-ne v1, v3, :cond_22

    .line 35727
    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v3, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 35729
    :cond_22
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x4

    if-ne v1, v4, :cond_30

    .line 35730
    const/4 v1, 0x3

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getSubjectBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 35732
    :cond_30
    const/4 v0, 0x0

    .local v0, i:I
    :goto_31
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_47

    .line 35733
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->activeOccupant_:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/google/protobuf/MessageLite;

    invoke-virtual {p1, v4, v1}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 35732
    add-int/lit8 v0, v0, 0x1

    goto :goto_31

    .line 35735
    :cond_47
    const/4 v0, 0x0

    :goto_48
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_5f

    .line 35736
    const/4 v2, 0x5

    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->inactiveOccupant_:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/google/protobuf/MessageLite;

    invoke-virtual {p1, v2, v1}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 35735
    add-int/lit8 v0, v0, 0x1

    goto :goto_48

    .line 35738
    :cond_5f
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x8

    if-ne v1, v5, :cond_6d

    .line 35739
    const/4 v1, 0x6

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getRoomDomainBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 35741
    :cond_6d
    const/4 v0, 0x0

    :goto_6e
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v1}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v1

    if-ge v0, v1, :cond_83

    .line 35742
    const/4 v1, 0x7

    iget-object v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v2, v0}, Lcom/google/protobuf/LazyStringList;->getByteString(I)Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 35741
    add-int/lit8 v0, v0, 0x1

    goto :goto_6e

    .line 35744
    :cond_83
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x10

    const/16 v2, 0x10

    if-ne v1, v2, :cond_94

    .line 35745
    iget-object v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->type_:Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;

    invoke-virtual {v1}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData$HangoutType;->getNumber()I

    move-result v1

    invoke-virtual {p1, v5, v1}, Lcom/google/protobuf/CodedOutputStream;->writeEnum(II)V

    .line 35747
    :cond_94
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x20

    const/16 v2, 0x20

    if-ne v1, v2, :cond_a3

    .line 35748
    const/16 v1, 0x9

    iget-boolean v2, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->idIsAutogenerated_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 35750
    :cond_a3
    iget v1, p0, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x40

    const/16 v2, 0x40

    if-ne v1, v2, :cond_b4

    .line 35751
    const/16 v1, 0xa

    invoke-direct {p0}, Lcom/google/wireless/tacotruck/proto/Data$HangoutData;->getBroadcastIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 35753
    :cond_b4
    return-void
.end method
