.class public final Lcom/google/apps/tacotown/proto/A2a$HangoutData;
.super Lcom/google/protobuf/GeneratedMessageLite;
.source "A2a.java"

# interfaces
.implements Lcom/google/apps/tacotown/proto/A2a$HangoutDataOrBuilder;


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/google/apps/tacotown/proto/A2a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "HangoutData"
.end annotation

.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;,
        Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;,
        Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetailsOrBuilder;,
        Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;,
        Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;
    }
.end annotation


# static fields
.field private static final defaultInstance:Lcom/google/apps/tacotown/proto/A2a$HangoutData;

.field private static final serialVersionUID:J


# instance fields
.field private bitField0_:I

.field private broadcastDetails_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

.field private broadcastId_:Ljava/lang/Object;

.field private broadcastTitle_:Ljava/lang/Object;

.field private hashedRoomId_:Ljava/lang/Object;

.field private idIsAutogenerated_:Z

.field private isActive_:Z

.field private isNoMinors_:Z

.field private isViewOnly_:Z

.field private joinType_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

.field private memoizedIsInitialized:B

.field private memoizedSerializedSize:I

.field private notificationId_:Lcom/google/protobuf/LazyStringList;

.field private occupantEver_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private occupant_:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;",
            ">;"
        }
    .end annotation
.end field

.field private preferredLanguage_:Ljava/lang/Object;

.field private region_:Ljava/lang/Object;

.field private roomDomain_:Ljava/lang/Object;

.field private roomId_:Ljava/lang/Object;

.field private subject_:Ljava/lang/Object;

.field private topicMaybeNsfw_:Z

.field private topicUrl_:Ljava/lang/Object;

.field private topic_:Ljava/lang/Object;

.field private type_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

.field private url_:Ljava/lang/Object;


# direct methods
.method static constructor <clinit>()V
    .registers 2

    .prologue
    .line 3123
    new-instance v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    const/4 v1, 0x1

    invoke-direct {v0, v1}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;-><init>(Z)V

    sput-object v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->defaultInstance:Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    .line 3124
    sget-object v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->defaultInstance:Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    invoke-direct {v0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->initFields()V

    .line 3125
    return-void
.end method

.method private constructor <init>(Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;)V
    .registers 3
    .parameter "builder"

    .prologue
    const/4 v0, -0x1

    .line 434
    invoke-direct {p0, p1}, Lcom/google/protobuf/GeneratedMessageLite;-><init>(Lcom/google/protobuf/GeneratedMessageLite$Builder;)V

    .line 1556
    iput-byte v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    .line 1656
    iput v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedSerializedSize:I

    .line 435
    return-void
.end method

.method synthetic constructor <init>(Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;Lcom/google/apps/tacotown/proto/A2a$1;)V
    .registers 3
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    invoke-direct {p0, p1}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;-><init>(Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;)V

    return-void
.end method

.method private constructor <init>(Z)V
    .registers 3
    .parameter "noInit"

    .prologue
    const/4 v0, -0x1

    .line 436
    invoke-direct {p0}, Lcom/google/protobuf/GeneratedMessageLite;-><init>()V

    .line 1556
    iput-byte v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    .line 1656
    iput v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedSerializedSize:I

    .line 436
    return-void
.end method

.method static synthetic access$1502(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$1602(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->url_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$1702(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->subject_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$1800(Lcom/google/apps/tacotown/proto/A2a$HangoutData;)Ljava/util/List;
    .registers 2
    .parameter "x0"

    .prologue
    .line 429
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    return-object v0
.end method

.method static synthetic access$1802(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/util/List;)Ljava/util/List;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    return-object p1
.end method

.method static synthetic access$1900(Lcom/google/apps/tacotown/proto/A2a$HangoutData;)Ljava/util/List;
    .registers 2
    .parameter "x0"

    .prologue
    .line 429
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    return-object v0
.end method

.method static synthetic access$1902(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/util/List;)Ljava/util/List;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    return-object p1
.end method

.method static synthetic access$2000(Lcom/google/apps/tacotown/proto/A2a$HangoutData;)Lcom/google/protobuf/LazyStringList;
    .registers 2
    .parameter "x0"

    .prologue
    .line 429
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object v0
.end method

.method static synthetic access$2002(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Lcom/google/protobuf/LazyStringList;)Lcom/google/protobuf/LazyStringList;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object p1
.end method

.method static synthetic access$2102(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;)Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->type_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

    return-object p1
.end method

.method static synthetic access$2202(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomDomain_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$2302(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-boolean p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->idIsAutogenerated_:Z

    return p1
.end method

.method static synthetic access$2402(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$2502(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastTitle_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$2602(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hashedRoomId_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$2702(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-boolean p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isActive_:Z

    return p1
.end method

.method static synthetic access$2802(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;)Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastDetails_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

    return-object p1
.end method

.method static synthetic access$2902(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-boolean p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isViewOnly_:Z

    return p1
.end method

.method static synthetic access$3002(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topic_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$3102(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicUrl_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$3202(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;)Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->joinType_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

    return-object p1
.end method

.method static synthetic access$3302(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-boolean p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isNoMinors_:Z

    return p1
.end method

.method static synthetic access$3402(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Z)Z
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-boolean p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicMaybeNsfw_:Z

    return p1
.end method

.method static synthetic access$3502(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->preferredLanguage_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$3602(Lcom/google/apps/tacotown/proto/A2a$HangoutData;Ljava/lang/Object;)Ljava/lang/Object;
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput-object p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->region_:Ljava/lang/Object;

    return-object p1
.end method

.method static synthetic access$3702(Lcom/google/apps/tacotown/proto/A2a$HangoutData;I)I
    .registers 2
    .parameter "x0"
    .parameter "x1"

    .prologue
    .line 429
    iput p1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    return p1
.end method

.method private getBroadcastIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1269
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 1270
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1271
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1273
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 1276
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getBroadcastTitleBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1301
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastTitle_:Ljava/lang/Object;

    .line 1302
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1303
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1305
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastTitle_:Ljava/lang/Object;

    .line 1308
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method public static getDefaultInstance()Lcom/google/apps/tacotown/proto/A2a$HangoutData;
    .registers 1

    .prologue
    .line 440
    sget-object v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->defaultInstance:Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    return-object v0
.end method

.method private getHashedRoomIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1333
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hashedRoomId_:Ljava/lang/Object;

    .line 1334
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1335
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1337
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hashedRoomId_:Ljava/lang/Object;

    .line 1340
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getPreferredLanguageBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1489
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->preferredLanguage_:Ljava/lang/Object;

    .line 1490
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1491
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1493
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->preferredLanguage_:Ljava/lang/Object;

    .line 1496
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getRegionBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1521
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->region_:Ljava/lang/Object;

    .line 1522
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1523
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1525
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->region_:Ljava/lang/Object;

    .line 1528
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getRoomDomainBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1227
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 1228
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1229
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1231
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 1234
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getRoomIdBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1065
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomId_:Ljava/lang/Object;

    .line 1066
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1067
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1069
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomId_:Ljava/lang/Object;

    .line 1072
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getSubjectBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1129
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->subject_:Ljava/lang/Object;

    .line 1130
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1131
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1133
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->subject_:Ljava/lang/Object;

    .line 1136
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getTopicBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1395
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topic_:Ljava/lang/Object;

    .line 1396
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1397
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1399
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topic_:Ljava/lang/Object;

    .line 1402
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getTopicUrlBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1427
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicUrl_:Ljava/lang/Object;

    .line 1428
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1429
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1431
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicUrl_:Ljava/lang/Object;

    .line 1434
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private getUrlBytes()Lcom/google/protobuf/ByteString;
    .registers 4

    .prologue
    .line 1097
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->url_:Ljava/lang/Object;

    .line 1098
    .local v1, ref:Ljava/lang/Object;
    instance-of v2, v1, Ljava/lang/String;

    if-eqz v2, :cond_f

    .line 1099
    check-cast v1, Ljava/lang/String;

    .end local v1           #ref:Ljava/lang/Object;
    invoke-static {v1}, Lcom/google/protobuf/ByteString;->copyFromUtf8(Ljava/lang/String;)Lcom/google/protobuf/ByteString;

    move-result-object v0

    .line 1101
    .local v0, b:Lcom/google/protobuf/ByteString;
    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->url_:Ljava/lang/Object;

    .line 1104
    .end local v0           #b:Lcom/google/protobuf/ByteString;
    :goto_e
    return-object v0

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_f
    check-cast v1, Lcom/google/protobuf/ByteString;

    .end local v1           #ref:Ljava/lang/Object;
    move-object v0, v1

    goto :goto_e
.end method

.method private initFields()V
    .registers 3

    .prologue
    const/4 v1, 0x0

    .line 1533
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomId_:Ljava/lang/Object;

    .line 1534
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->url_:Ljava/lang/Object;

    .line 1535
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->subject_:Ljava/lang/Object;

    .line 1536
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    .line 1537
    invoke-static {}, Ljava/util/Collections;->emptyList()Ljava/util/List;

    move-result-object v0

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    .line 1538
    sget-object v0, Lcom/google/protobuf/LazyStringArrayList;->EMPTY:Lcom/google/protobuf/LazyStringList;

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    .line 1539
    sget-object v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;->CONSUMER:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->type_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

    .line 1540
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 1541
    const/4 v0, 0x1

    iput-boolean v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->idIsAutogenerated_:Z

    .line 1542
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 1543
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastTitle_:Ljava/lang/Object;

    .line 1544
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hashedRoomId_:Ljava/lang/Object;

    .line 1545
    iput-boolean v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isActive_:Z

    .line 1546
    invoke-static {}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;->getDefaultInstance()Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

    move-result-object v0

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastDetails_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

    .line 1547
    iput-boolean v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isViewOnly_:Z

    .line 1548
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topic_:Ljava/lang/Object;

    .line 1549
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicUrl_:Ljava/lang/Object;

    .line 1550
    sget-object v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;->ORIGINAL:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->joinType_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

    .line 1551
    iput-boolean v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isNoMinors_:Z

    .line 1552
    iput-boolean v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicMaybeNsfw_:Z

    .line 1553
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->preferredLanguage_:Ljava/lang/Object;

    .line 1554
    const-string v0, ""

    iput-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->region_:Ljava/lang/Object;

    .line 1555
    return-void
.end method

.method public static newBuilder()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;
    .registers 1

    .prologue
    .line 1833
    #calls: Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;->create()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;
    invoke-static {}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;->access$1300()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public static newBuilder(Lcom/google/apps/tacotown/proto/A2a$HangoutData;)Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;
    .registers 2
    .parameter "prototype"

    .prologue
    .line 1836
    invoke-static {}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->newBuilder()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {v0, p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;->mergeFrom(Lcom/google/apps/tacotown/proto/A2a$HangoutData;)Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public static parseFrom([B)Lcom/google/apps/tacotown/proto/A2a$HangoutData;
    .registers 2
    .parameter "data"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/google/protobuf/InvalidProtocolBufferException;
        }
    .end annotation

    .prologue
    .line 1780
    invoke-static {}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->newBuilder()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    invoke-virtual {v0, p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;->mergeFrom([B)Lcom/google/protobuf/AbstractMessageLite$Builder;

    move-result-object v0

    check-cast v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    #calls: Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;->buildParsed()Lcom/google/apps/tacotown/proto/A2a$HangoutData;
    invoke-static {v0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;->access$1200(Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;)Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    move-result-object v0

    return-object v0
.end method


# virtual methods
.method public getBroadcastDetails()Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;
    .registers 2

    .prologue
    .line 1361
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastDetails_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

    return-object v0
.end method

.method public getBroadcastId()Ljava/lang/String;
    .registers 5
    .annotation runtime Ljava/lang/Deprecated;
    .end annotation

    .prologue
    .line 1255
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastId_:Ljava/lang/Object;

    .line 1256
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1257
    check-cast v1, Ljava/lang/String;

    .line 1265
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1259
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1261
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1262
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1263
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1265
    goto :goto_8
.end method

.method public getBroadcastTitle()Ljava/lang/String;
    .registers 5
    .annotation runtime Ljava/lang/Deprecated;
    .end annotation

    .prologue
    .line 1287
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastTitle_:Ljava/lang/Object;

    .line 1288
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1289
    check-cast v1, Ljava/lang/String;

    .line 1297
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1291
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1293
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1294
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1295
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastTitle_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1297
    goto :goto_8
.end method

.method public getDefaultInstanceForType()Lcom/google/apps/tacotown/proto/A2a$HangoutData;
    .registers 2

    .prologue
    .line 444
    sget-object v0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->defaultInstance:Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    return-object v0
.end method

.method public bridge synthetic getDefaultInstanceForType()Lcom/google/protobuf/MessageLite;
    .registers 2

    .prologue
    .line 429
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getDefaultInstanceForType()Lcom/google/apps/tacotown/proto/A2a$HangoutData;

    move-result-object v0

    return-object v0
.end method

.method public getHashedRoomId()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1319
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hashedRoomId_:Ljava/lang/Object;

    .line 1320
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1321
    check-cast v1, Ljava/lang/String;

    .line 1329
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1323
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1325
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1326
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1327
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hashedRoomId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1329
    goto :goto_8
.end method

.method public getIdIsAutogenerated()Z
    .registers 2

    .prologue
    .line 1245
    iget-boolean v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->idIsAutogenerated_:Z

    return v0
.end method

.method public getIsActive()Z
    .registers 2

    .prologue
    .line 1351
    iget-boolean v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isActive_:Z

    return v0
.end method

.method public getIsNoMinors()Z
    .registers 2

    .prologue
    .line 1455
    iget-boolean v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isNoMinors_:Z

    return v0
.end method

.method public getIsViewOnly()Z
    .registers 2

    .prologue
    .line 1371
    iget-boolean v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isViewOnly_:Z

    return v0
.end method

.method public getJoinType()Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;
    .registers 2

    .prologue
    .line 1445
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->joinType_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

    return-object v0
.end method

.method public getNotificationIdList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .prologue
    .line 1187
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    return-object v0
.end method

.method public getOccupant(I)Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 1154
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;

    return-object v0
.end method

.method public getOccupantCount()I
    .registers 2

    .prologue
    .line 1151
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getOccupantEver(I)Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;
    .registers 3
    .parameter "index"

    .prologue
    .line 1175
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;

    return-object v0
.end method

.method public getOccupantEverCount()I
    .registers 2

    .prologue
    .line 1172
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->size()I

    move-result v0

    return v0
.end method

.method public getOccupantList()Ljava/util/List;
    .registers 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;",
            ">;"
        }
    .end annotation

    .prologue
    .line 1144
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    return-object v0
.end method

.method public getPreferredLanguage()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1475
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->preferredLanguage_:Ljava/lang/Object;

    .line 1476
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1477
    check-cast v1, Ljava/lang/String;

    .line 1485
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1479
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1481
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1482
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1483
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->preferredLanguage_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1485
    goto :goto_8
.end method

.method public getRegion()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1507
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->region_:Ljava/lang/Object;

    .line 1508
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1509
    check-cast v1, Ljava/lang/String;

    .line 1517
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1511
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1513
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1514
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1515
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->region_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1517
    goto :goto_8
.end method

.method public getRoomDomain()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1213
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomDomain_:Ljava/lang/Object;

    .line 1214
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1215
    check-cast v1, Ljava/lang/String;

    .line 1223
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1217
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1219
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1220
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1221
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomDomain_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1223
    goto :goto_8
.end method

.method public getRoomId()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1051
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomId_:Ljava/lang/Object;

    .line 1052
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1053
    check-cast v1, Ljava/lang/String;

    .line 1061
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1055
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1057
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1058
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1059
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->roomId_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1061
    goto :goto_8
.end method

.method public getSerializedSize()I
    .registers 11

    .prologue
    const/16 v9, 0x10

    const/16 v8, 0x8

    const/4 v7, 0x4

    const/4 v6, 0x2

    const/4 v5, 0x1

    .line 1658
    iget v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedSerializedSize:I

    .line 1659
    .local v2, size:I
    const/4 v4, -0x1

    if-eq v2, v4, :cond_e

    move v3, v2

    .line 1756
    .end local v2           #size:I
    .local v3, size:I
    :goto_d
    return v3

    .line 1661
    .end local v3           #size:I
    .restart local v2       #size:I
    :cond_e
    const/4 v2, 0x0

    .line 1662
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x1

    if-ne v4, v5, :cond_1e

    .line 1663
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v5, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1666
    :cond_1e
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x2

    if-ne v4, v6, :cond_2d

    .line 1667
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v6, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1670
    :cond_2d
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x4

    if-ne v4, v7, :cond_3d

    .line 1671
    const/4 v4, 0x3

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getSubjectBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1674
    :cond_3d
    const/4 v1, 0x0

    .local v1, i:I
    :goto_3e
    iget-object v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    if-ge v1, v4, :cond_56

    .line 1675
    iget-object v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    invoke-interface {v4, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lcom/google/protobuf/MessageLite;

    invoke-static {v7, v4}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1674
    add-int/lit8 v1, v1, 0x1

    goto :goto_3e

    .line 1678
    :cond_56
    const/4 v1, 0x0

    :goto_57
    iget-object v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    if-ge v1, v4, :cond_70

    .line 1679
    const/4 v5, 0x5

    iget-object v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    invoke-interface {v4, v1}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v4

    check-cast v4, Lcom/google/protobuf/MessageLite;

    invoke-static {v5, v4}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1678
    add-int/lit8 v1, v1, 0x1

    goto :goto_57

    .line 1683
    :cond_70
    const/4 v0, 0x0

    .line 1684
    .local v0, dataSize:I
    const/4 v1, 0x0

    :goto_72
    iget-object v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v4}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v4

    if-ge v1, v4, :cond_88

    .line 1685
    iget-object v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v4, v1}, Lcom/google/protobuf/LazyStringList;->getByteString(I)Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSizeNoTag(Lcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v0, v4

    .line 1684
    add-int/lit8 v1, v1, 0x1

    goto :goto_72

    .line 1688
    :cond_88
    add-int/2addr v2, v0

    .line 1689
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getNotificationIdList()Ljava/util/List;

    move-result-object v4

    invoke-interface {v4}, Ljava/util/List;->size()I

    move-result v4

    mul-int/lit8 v4, v4, 0x1

    add-int/2addr v2, v4

    .line 1691
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x8

    if-ne v4, v8, :cond_a6

    .line 1692
    const/4 v4, 0x7

    iget-object v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->type_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

    invoke-virtual {v5}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;->getNumber()I

    move-result v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeEnumSize(II)I

    move-result v4

    add-int/2addr v2, v4

    .line 1695
    :cond_a6
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x10

    if-ne v4, v9, :cond_b5

    .line 1696
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getRoomDomainBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v8, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1699
    :cond_b5
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x20

    const/16 v5, 0x20

    if-ne v4, v5, :cond_c6

    .line 1700
    const/16 v4, 0x9

    iget-boolean v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->idIsAutogenerated_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 1703
    :cond_c6
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v4, v4, 0x40

    const/16 v5, 0x40

    if-ne v4, v5, :cond_d9

    .line 1704
    const/16 v4, 0xa

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getBroadcastIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1707
    :cond_d9
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x80

    const/16 v5, 0x80

    if-ne v4, v5, :cond_ec

    .line 1708
    const/16 v4, 0xb

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getBroadcastTitleBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1711
    :cond_ec
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x100

    const/16 v5, 0x100

    if-ne v4, v5, :cond_ff

    .line 1712
    const/16 v4, 0xc

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getHashedRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1715
    :cond_ff
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x200

    const/16 v5, 0x200

    if-ne v4, v5, :cond_110

    .line 1716
    const/16 v4, 0xd

    iget-boolean v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isActive_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 1719
    :cond_110
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x400

    const/16 v5, 0x400

    if-ne v4, v5, :cond_121

    .line 1720
    const/16 v4, 0xe

    iget-object v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastDetails_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeMessageSize(ILcom/google/protobuf/MessageLite;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1723
    :cond_121
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x800

    const/16 v5, 0x800

    if-ne v4, v5, :cond_132

    .line 1724
    const/16 v4, 0xf

    iget-boolean v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isViewOnly_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 1727
    :cond_132
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x1000

    const/16 v5, 0x1000

    if-ne v4, v5, :cond_143

    .line 1728
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getTopicBytes()Lcom/google/protobuf/ByteString;

    move-result-object v4

    invoke-static {v9, v4}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1731
    :cond_143
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x2000

    const/16 v5, 0x2000

    if-ne v4, v5, :cond_156

    .line 1732
    const/16 v4, 0x11

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getTopicUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1735
    :cond_156
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v4, v4, 0x4000

    const/16 v5, 0x4000

    if-ne v4, v5, :cond_16b

    .line 1736
    const/16 v4, 0x12

    iget-object v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->joinType_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

    invoke-virtual {v5}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;->getNumber()I

    move-result v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeEnumSize(II)I

    move-result v4

    add-int/2addr v2, v4

    .line 1739
    :cond_16b
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const v5, 0x8000

    and-int/2addr v4, v5

    const v5, 0x8000

    if-ne v4, v5, :cond_17f

    .line 1740
    const/16 v4, 0x13

    iget-boolean v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isNoMinors_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 1743
    :cond_17f
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const/high16 v5, 0x1

    and-int/2addr v4, v5

    const/high16 v5, 0x1

    if-ne v4, v5, :cond_191

    .line 1744
    const/16 v4, 0x14

    iget-boolean v5, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicMaybeNsfw_:Z

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBoolSize(IZ)I

    move-result v4

    add-int/2addr v2, v4

    .line 1747
    :cond_191
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const/high16 v5, 0x2

    and-int/2addr v4, v5

    const/high16 v5, 0x2

    if-ne v4, v5, :cond_1a5

    .line 1748
    const/16 v4, 0x15

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getPreferredLanguageBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1751
    :cond_1a5
    iget v4, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const/high16 v5, 0x4

    and-int/2addr v4, v5

    const/high16 v5, 0x4

    if-ne v4, v5, :cond_1b9

    .line 1752
    const/16 v4, 0x16

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getRegionBytes()Lcom/google/protobuf/ByteString;

    move-result-object v5

    invoke-static {v4, v5}, Lcom/google/protobuf/CodedOutputStream;->computeBytesSize(ILcom/google/protobuf/ByteString;)I

    move-result v4

    add-int/2addr v2, v4

    .line 1755
    :cond_1b9
    iput v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedSerializedSize:I

    move v3, v2

    .line 1756
    .end local v2           #size:I
    .restart local v3       #size:I
    goto/16 :goto_d
.end method

.method public getSubject()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1115
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->subject_:Ljava/lang/Object;

    .line 1116
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1117
    check-cast v1, Ljava/lang/String;

    .line 1125
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1119
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1121
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1122
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1123
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->subject_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1125
    goto :goto_8
.end method

.method public getTopic()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1381
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topic_:Ljava/lang/Object;

    .line 1382
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1383
    check-cast v1, Ljava/lang/String;

    .line 1391
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1385
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1387
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1388
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1389
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topic_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1391
    goto :goto_8
.end method

.method public getTopicMaybeNsfw()Z
    .registers 2

    .prologue
    .line 1465
    iget-boolean v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicMaybeNsfw_:Z

    return v0
.end method

.method public getTopicUrl()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1413
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicUrl_:Ljava/lang/Object;

    .line 1414
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1415
    check-cast v1, Ljava/lang/String;

    .line 1423
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1417
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1419
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1420
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1421
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicUrl_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1423
    goto :goto_8
.end method

.method public getType()Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;
    .registers 2

    .prologue
    .line 1203
    iget-object v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->type_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

    return-object v0
.end method

.method public getUrl()Ljava/lang/String;
    .registers 5

    .prologue
    .line 1083
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->url_:Ljava/lang/Object;

    .line 1084
    .local v1, ref:Ljava/lang/Object;
    instance-of v3, v1, Ljava/lang/String;

    if-eqz v3, :cond_9

    .line 1085
    check-cast v1, Ljava/lang/String;

    .line 1093
    .end local v1           #ref:Ljava/lang/Object;
    :goto_8
    return-object v1

    .restart local v1       #ref:Ljava/lang/Object;
    :cond_9
    move-object v0, v1

    .line 1087
    check-cast v0, Lcom/google/protobuf/ByteString;

    .line 1089
    .local v0, bs:Lcom/google/protobuf/ByteString;
    invoke-virtual {v0}, Lcom/google/protobuf/ByteString;->toStringUtf8()Ljava/lang/String;

    move-result-object v2

    .line 1090
    .local v2, s:Ljava/lang/String;
    invoke-static {v0}, Lcom/google/protobuf/Internal;->isValidUtf8(Lcom/google/protobuf/ByteString;)Z

    move-result v3

    if-eqz v3, :cond_18

    .line 1091
    iput-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->url_:Ljava/lang/Object;

    :cond_18
    move-object v1, v2

    .line 1093
    goto :goto_8
.end method

.method public hasBroadcastDetails()Z
    .registers 3

    .prologue
    .line 1358
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x400

    const/16 v1, 0x400

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasBroadcastId()Z
    .registers 3
    .annotation runtime Ljava/lang/Deprecated;
    .end annotation

    .prologue
    .line 1252
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x40

    const/16 v1, 0x40

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasBroadcastTitle()Z
    .registers 3
    .annotation runtime Ljava/lang/Deprecated;
    .end annotation

    .prologue
    .line 1284
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x80

    const/16 v1, 0x80

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasHashedRoomId()Z
    .registers 3

    .prologue
    .line 1316
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x100

    const/16 v1, 0x100

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIdIsAutogenerated()Z
    .registers 3

    .prologue
    .line 1242
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x20

    const/16 v1, 0x20

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIsActive()Z
    .registers 3

    .prologue
    .line 1348
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x200

    const/16 v1, 0x200

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIsNoMinors()Z
    .registers 3

    .prologue
    const v1, 0x8000

    .line 1452
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/2addr v0, v1

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasIsViewOnly()Z
    .registers 3

    .prologue
    .line 1368
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x800

    const/16 v1, 0x800

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasJoinType()Z
    .registers 3

    .prologue
    .line 1442
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x4000

    const/16 v1, 0x4000

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasPreferredLanguage()Z
    .registers 3

    .prologue
    const/high16 v1, 0x2

    .line 1472
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/2addr v0, v1

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasRegion()Z
    .registers 3

    .prologue
    const/high16 v1, 0x4

    .line 1504
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/2addr v0, v1

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasRoomDomain()Z
    .registers 3

    .prologue
    .line 1210
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x10

    const/16 v1, 0x10

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasRoomId()Z
    .registers 3

    .prologue
    const/4 v0, 0x1

    .line 1048
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v0, :cond_8

    :goto_7
    return v0

    :cond_8
    const/4 v0, 0x0

    goto :goto_7
.end method

.method public hasSubject()Z
    .registers 3

    .prologue
    .line 1112
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x4

    const/4 v1, 0x4

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasTopic()Z
    .registers 3

    .prologue
    .line 1378
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x1000

    const/16 v1, 0x1000

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasTopicMaybeNsfw()Z
    .registers 3

    .prologue
    const/high16 v1, 0x1

    .line 1462
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/2addr v0, v1

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public hasTopicUrl()Z
    .registers 3

    .prologue
    .line 1410
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v0, v0, 0x2000

    const/16 v1, 0x2000

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasType()Z
    .registers 3

    .prologue
    .line 1200
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x8

    const/16 v1, 0x8

    if-ne v0, v1, :cond_a

    const/4 v0, 0x1

    :goto_9
    return v0

    :cond_a
    const/4 v0, 0x0

    goto :goto_9
.end method

.method public hasUrl()Z
    .registers 3

    .prologue
    .line 1080
    iget v0, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v0, v0, 0x2

    const/4 v1, 0x2

    if-ne v0, v1, :cond_9

    const/4 v0, 0x1

    :goto_8
    return v0

    :cond_9
    const/4 v0, 0x0

    goto :goto_8
.end method

.method public final isInitialized()Z
    .registers 6

    .prologue
    const/4 v2, 0x1

    const/4 v3, 0x0

    .line 1558
    iget-byte v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    .line 1559
    .local v1, isInitialized:B
    const/4 v4, -0x1

    if-eq v1, v4, :cond_d

    if-ne v1, v2, :cond_b

    :goto_9
    move v3, v2

    .line 1582
    :goto_a
    return v3

    :cond_b
    move v2, v3

    .line 1559
    goto :goto_9

    .line 1561
    :cond_d
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hasRoomId()Z

    move-result v4

    if-nez v4, :cond_16

    .line 1562
    iput-byte v3, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    goto :goto_a

    .line 1565
    :cond_16
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->hasUrl()Z

    move-result v4

    if-nez v4, :cond_1f

    .line 1566
    iput-byte v3, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    goto :goto_a

    .line 1569
    :cond_1f
    const/4 v0, 0x0

    .local v0, i:I
    :goto_20
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getOccupantCount()I

    move-result v4

    if-ge v0, v4, :cond_36

    .line 1570
    invoke-virtual {p0, v0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getOccupant(I)Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;

    move-result-object v4

    invoke-virtual {v4}, Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;->isInitialized()Z

    move-result v4

    if-nez v4, :cond_33

    .line 1571
    iput-byte v3, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    goto :goto_a

    .line 1569
    :cond_33
    add-int/lit8 v0, v0, 0x1

    goto :goto_20

    .line 1575
    :cond_36
    const/4 v0, 0x0

    :goto_37
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getOccupantEverCount()I

    move-result v4

    if-ge v0, v4, :cond_4d

    .line 1576
    invoke-virtual {p0, v0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getOccupantEver(I)Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;

    move-result-object v4

    invoke-virtual {v4}, Lcom/google/apps/tacotown/proto/A2a$HangoutOccupant;->isInitialized()Z

    move-result v4

    if-nez v4, :cond_4a

    .line 1577
    iput-byte v3, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    goto :goto_a

    .line 1575
    :cond_4a
    add-int/lit8 v0, v0, 0x1

    goto :goto_37

    .line 1581
    :cond_4d
    iput-byte v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->memoizedIsInitialized:B

    move v3, v2

    .line 1582
    goto :goto_a
.end method

.method public newBuilderForType()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;
    .registers 2

    .prologue
    .line 1834
    invoke-static {}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->newBuilder()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic newBuilderForType()Lcom/google/protobuf/MessageLite$Builder;
    .registers 2

    .prologue
    .line 429
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->newBuilderForType()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public toBuilder()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;
    .registers 2

    .prologue
    .line 1838
    invoke-static {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->newBuilder(Lcom/google/apps/tacotown/proto/A2a$HangoutData;)Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method public bridge synthetic toBuilder()Lcom/google/protobuf/MessageLite$Builder;
    .registers 2

    .prologue
    .line 429
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->toBuilder()Lcom/google/apps/tacotown/proto/A2a$HangoutData$Builder;

    move-result-object v0

    return-object v0
.end method

.method protected writeReplace()Ljava/lang/Object;
    .registers 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/ObjectStreamException;
        }
    .end annotation

    .prologue
    .line 1763
    invoke-super {p0}, Lcom/google/protobuf/GeneratedMessageLite;->writeReplace()Ljava/lang/Object;

    move-result-object v0

    return-object v0
.end method

.method public writeTo(Lcom/google/protobuf/CodedOutputStream;)V
    .registers 9
    .parameter "output"
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    const/16 v6, 0x10

    const/16 v5, 0x8

    const/4 v4, 0x4

    const/4 v3, 0x2

    const/4 v2, 0x1

    .line 1587
    invoke-virtual {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getSerializedSize()I

    .line 1588
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x1

    if-ne v1, v2, :cond_17

    .line 1589
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v2, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1591
    :cond_17
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x2

    if-ne v1, v3, :cond_24

    .line 1592
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v3, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1594
    :cond_24
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x4

    if-ne v1, v4, :cond_32

    .line 1595
    const/4 v1, 0x3

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getSubjectBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1597
    :cond_32
    const/4 v0, 0x0

    .local v0, i:I
    :goto_33
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_49

    .line 1598
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupant_:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/google/protobuf/MessageLite;

    invoke-virtual {p1, v4, v1}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 1597
    add-int/lit8 v0, v0, 0x1

    goto :goto_33

    .line 1600
    :cond_49
    const/4 v0, 0x0

    :goto_4a
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v1

    if-ge v0, v1, :cond_61

    .line 1601
    const/4 v2, 0x5

    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->occupantEver_:Ljava/util/List;

    invoke-interface {v1, v0}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lcom/google/protobuf/MessageLite;

    invoke-virtual {p1, v2, v1}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 1600
    add-int/lit8 v0, v0, 0x1

    goto :goto_4a

    .line 1603
    :cond_61
    const/4 v0, 0x0

    :goto_62
    iget-object v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v1}, Lcom/google/protobuf/LazyStringList;->size()I

    move-result v1

    if-ge v0, v1, :cond_77

    .line 1604
    const/4 v1, 0x6

    iget-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->notificationId_:Lcom/google/protobuf/LazyStringList;

    invoke-interface {v2, v0}, Lcom/google/protobuf/LazyStringList;->getByteString(I)Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1603
    add-int/lit8 v0, v0, 0x1

    goto :goto_62

    .line 1606
    :cond_77
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x8

    if-ne v1, v5, :cond_87

    .line 1607
    const/4 v1, 0x7

    iget-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->type_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;

    invoke-virtual {v2}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutType;->getNumber()I

    move-result v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeEnum(II)V

    .line 1609
    :cond_87
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x10

    if-ne v1, v6, :cond_94

    .line 1610
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getRoomDomainBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v5, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1612
    :cond_94
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x20

    const/16 v2, 0x20

    if-ne v1, v2, :cond_a3

    .line 1613
    const/16 v1, 0x9

    iget-boolean v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->idIsAutogenerated_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 1615
    :cond_a3
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit8 v1, v1, 0x40

    const/16 v2, 0x40

    if-ne v1, v2, :cond_b4

    .line 1616
    const/16 v1, 0xa

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getBroadcastIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1618
    :cond_b4
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x80

    const/16 v2, 0x80

    if-ne v1, v2, :cond_c5

    .line 1619
    const/16 v1, 0xb

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getBroadcastTitleBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1621
    :cond_c5
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x100

    const/16 v2, 0x100

    if-ne v1, v2, :cond_d6

    .line 1622
    const/16 v1, 0xc

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getHashedRoomIdBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1624
    :cond_d6
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x200

    const/16 v2, 0x200

    if-ne v1, v2, :cond_e5

    .line 1625
    const/16 v1, 0xd

    iget-boolean v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isActive_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 1627
    :cond_e5
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x400

    const/16 v2, 0x400

    if-ne v1, v2, :cond_f4

    .line 1628
    const/16 v1, 0xe

    iget-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->broadcastDetails_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$BroadcastDetails;

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeMessage(ILcom/google/protobuf/MessageLite;)V

    .line 1630
    :cond_f4
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x800

    const/16 v2, 0x800

    if-ne v1, v2, :cond_103

    .line 1631
    const/16 v1, 0xf

    iget-boolean v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isViewOnly_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 1633
    :cond_103
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x1000

    const/16 v2, 0x1000

    if-ne v1, v2, :cond_112

    .line 1634
    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getTopicBytes()Lcom/google/protobuf/ByteString;

    move-result-object v1

    invoke-virtual {p1, v6, v1}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1636
    :cond_112
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x2000

    const/16 v2, 0x2000

    if-ne v1, v2, :cond_123

    .line 1637
    const/16 v1, 0x11

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getTopicUrlBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1639
    :cond_123
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    and-int/lit16 v1, v1, 0x4000

    const/16 v2, 0x4000

    if-ne v1, v2, :cond_136

    .line 1640
    const/16 v1, 0x12

    iget-object v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->joinType_:Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;

    invoke-virtual {v2}, Lcom/google/apps/tacotown/proto/A2a$HangoutData$HangoutJoinType;->getNumber()I

    move-result v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeEnum(II)V

    .line 1642
    :cond_136
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const v2, 0x8000

    and-int/2addr v1, v2

    const v2, 0x8000

    if-ne v1, v2, :cond_148

    .line 1643
    const/16 v1, 0x13

    iget-boolean v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->isNoMinors_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 1645
    :cond_148
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const/high16 v2, 0x1

    and-int/2addr v1, v2

    const/high16 v2, 0x1

    if-ne v1, v2, :cond_158

    .line 1646
    const/16 v1, 0x14

    iget-boolean v2, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->topicMaybeNsfw_:Z

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBool(IZ)V

    .line 1648
    :cond_158
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const/high16 v2, 0x2

    and-int/2addr v1, v2

    const/high16 v2, 0x2

    if-ne v1, v2, :cond_16a

    .line 1649
    const/16 v1, 0x15

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getPreferredLanguageBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1651
    :cond_16a
    iget v1, p0, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->bitField0_:I

    const/high16 v2, 0x4

    and-int/2addr v1, v2

    const/high16 v2, 0x4

    if-ne v1, v2, :cond_17c

    .line 1652
    const/16 v1, 0x16

    invoke-direct {p0}, Lcom/google/apps/tacotown/proto/A2a$HangoutData;->getRegionBytes()Lcom/google/protobuf/ByteString;

    move-result-object v2

    invoke-virtual {p1, v1, v2}, Lcom/google/protobuf/CodedOutputStream;->writeBytes(ILcom/google/protobuf/ByteString;)V

    .line 1654
    :cond_17c
    return-void
.end method
