#!/system/bin/sh

LOG_FILE=/data/zipalign.log
DB=/data/zipalign.db

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

if [ ! -f $DB ]; then
	touch $DB;
fi;

echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE

for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $DB ] && [ $(grep "$DIR/$APK" $DB|wc -l) -gt 0 ] ; then
      echo "$DIR/$APK has already been checked" | tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "$DIR/$APK is already aligned" | tee -a $LOG_FILE
        grep "$DIR/$APK" $DB > /dev/null || echo $DIR/$APK >> $DB
      else
        echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $DB > /dev/null || echo $DIR/$APK >> $DB
      fi
    fi
  done
done

busybox mount -o ro,remount /system
touch $DB
echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE
