.class public Lorg/apache/commons/httpclient/Header;
.super Lorg/apache/commons/httpclient/NameValuePair;
.source "Header.java"


# instance fields
.field private isAutogenerated:Z


# direct methods
.method public constructor <init>()V
    .registers 2

    .prologue
    const/4 v0, 0x0

    .line 54
    invoke-direct {p0, v0, v0}, Lorg/apache/commons/httpclient/Header;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    .line 55
    return-void
.end method

.method public constructor <init>(Ljava/lang/String;Ljava/lang/String;)V
    .registers 4
    .parameter "name"
    .parameter "value"

    .prologue
    .line 64
    invoke-direct {p0, p1, p2}, Lorg/apache/commons/httpclient/NameValuePair;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    .line 48
    const/4 v0, 0x0

    iput-boolean v0, p0, Lorg/apache/commons/httpclient/Header;->isAutogenerated:Z

    .line 65
    return-void
.end method

.method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Z)V
    .registers 5
    .parameter "name"
    .parameter "value"
    .parameter "isAutogenerated"

    .prologue
    .line 78
    invoke-direct {p0, p1, p2}, Lorg/apache/commons/httpclient/NameValuePair;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    .line 48
    const/4 v0, 0x0

    iput-boolean v0, p0, Lorg/apache/commons/httpclient/Header;->isAutogenerated:Z

    .line 79
    iput-boolean p3, p0, Lorg/apache/commons/httpclient/Header;->isAutogenerated:Z

    .line 80
    return-void
.end method


# virtual methods
.method public getElements()[Lorg/apache/commons/httpclient/HeaderElement;
    .registers 2

    .prologue
    .line 130
    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->getValue()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Lorg/apache/commons/httpclient/HeaderElement;->parseElements(Ljava/lang/String;)[Lorg/apache/commons/httpclient/HeaderElement;

    move-result-object v0

    return-object v0
.end method

.method public getValues()[Lorg/apache/commons/httpclient/HeaderElement;
    .registers 2
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lorg/apache/commons/httpclient/HttpException;
        }
    .end annotation

    .prologue
    .line 116
    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->getValue()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Lorg/apache/commons/httpclient/HeaderElement;->parse(Ljava/lang/String;)[Lorg/apache/commons/httpclient/HeaderElement;

    move-result-object v0

    return-object v0
.end method

.method public isAutogenerated()Z
    .registers 2

    .prologue
    .line 142
    iget-boolean v0, p0, Lorg/apache/commons/httpclient/Header;->isAutogenerated:Z

    return v0
.end method

.method public toExternalForm()Ljava/lang/String;
    .registers 3

    .prologue
    .line 90
    new-instance v1, Ljava/lang/StringBuffer;

    invoke-direct {v1}, Ljava/lang/StringBuffer;-><init>()V

    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->getName()Ljava/lang/String;

    move-result-object v0

    if-nez v0, :cond_2e

    const-string v0, ""

    :goto_d
    invoke-virtual {v1, v0}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v0

    const-string v1, ": "

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v1

    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->getValue()Ljava/lang/String;

    move-result-object v0

    if-nez v0, :cond_33

    const-string v0, ""

    :goto_1f
    invoke-virtual {v1, v0}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v0

    const-string v1, "\r\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;

    move-result-object v0

    return-object v0

    :cond_2e
    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->getName()Ljava/lang/String;

    move-result-object v0

    goto :goto_d

    :cond_33
    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->getValue()Ljava/lang/String;

    move-result-object v0

    goto :goto_1f
.end method

.method public toString()Ljava/lang/String;
    .registers 2

    .prologue
    .line 102
    invoke-virtual {p0}, Lorg/apache/commons/httpclient/Header;->toExternalForm()Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method
